### ISSUE TITLE
Android - add benchmarks section

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#111]
Add benchmarks section (speedometer for now, reporting from bitbar, when available)

**Comment by armenzg** [comment]
@stuartphilp @jmaher I believe there's nothing to be done in here until we have speedometer on bitbar.
What is the timeline for this?

**Comment by jmaher** [comment]
lets say 2 weeks for the data

**Comment by armenzg** [comment]
We've added Speedometer.
