### ISSUE TITLE
Android - Talos section

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#112]
Add talos section (include tp6 and any other tests that are running in bitbar, when available)

**Comment by armenzg** [comment]
@jmaher what is the timeline to running tp6 on Android? Any bug to follow?

**Comment by jmaher** [comment]
tp6 on android will be longer term (August or later)

**Comment by armenzg** [comment]
Let's file something once we have it running.
