### ISSUE TITLE
Clean up dashboards to be readable from mobile devices

### ISSUE THREAD

**Issue by stuartphilp** [mozilla-frontend-infra/firefox-health-dashboard#115]
To make it more readable from phones, consider how we can display the dashboards responsively and clean up any rendering bugs

![img_4f4095458ef9-1](https://user-images.githubusercontent.com/2964961/41675322-6442cba8-7490-11e8-819c-f68e3e4c6d86.jpeg)

**Comment by armenzg** [comment]
This has been fixed.
<img width="376" alt="image" src="https://user-images.githubusercontent.com/44410/47310380-eda49680-d604-11e8-9388-e45441d06304.png">
