### ISSUE TITLE
Move to CSS grids

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#120]
We currently have tons flexbox in our CSS.
We should move to CSS grids.

**Comment by a8t** [comment]
Hi, I'm willing to take this on. I'm wondering how you feel about browser compatibility. Should I leave the flexbox as a fallback?

**Comment by armenzg** [comment]
Hi Andy,
I've received an email from GH saying that you made a comment, however, I can't see your comment on this page and I can't see anything about being deleted.

Here's your comment (via email):
> Hi, I'm willing to take this on. I'm wondering how you feel about browser compatibility. Should I leave the flexbox as a fallback?

No need for backward compatibility as this site is mainly used for Firefox product managers and engineers. They should be using Firefox Nightly 😄

**Comment by armenzg** [comment]
After I filed this issue I realized that there's no need to move from flexbox to CSS grids. They both have their own purposes and one is not replacing the other one. I'm going to close this issue.
