### ISSUE TITLE
Invert JetStream graph

### ISSUE THREAD

**Issue by cpeterso** [mozilla-frontend-infra/firefox-health-dashboard#130]
The JetStream benchmark reports a ["higher is faster" score](https://www.browserbench.org/JetStream/) instead of a "lower is faster" elapsed time like the other benchmarks on the Quantum dashboard. We should invert the JetStream graph so "_visually_ lower is faster" like all the other graphs on the page. We do for AWFY.

**Comment by armenzg** [comment]
I will tackle this after the usability issue.

As reference:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/44410/42969213-7cfdb096-8b73-11e8-9c5a-a4997476dbfd.png">

**Comment by armenzg** [comment]
We're going to switch to ChartJs based graphs that automatically reverse graphs depending if their metadata in Perfherder says 'lower_is_better'.

Here's a screenshot showing you the inverted JetStream:
<img width="916" alt="image" src="https://user-images.githubusercontent.com/44410/47462916-c25faa00-d7b2-11e8-8773-71dc67a29a65.png">

**Comment by klahnakoski** [comment]
This has been fixed. at the very least the `lower_is_better` is passed through to the chart rendering so the right thing can be done.
