### ISSUE TITLE
Provide some guidance on reading charts

### ISSUE THREAD

**Issue by mgaudet** [mozilla-frontend-infra/firefox-health-dashboard#131]
Related to #130, if the design is such that lower should be be always better, might be nice to have a sentence to that effect, or some other indicator somewhere to help new people navigate the dashboard.

**Comment by armenzg** [comment]
This will be fixed when we change the quantum page components to the ones I've written recently that "lower is always better".

**Comment by armenzg** [comment]
I've fixed this today:
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/44410/48276412-f1625680-e415-11e8-8296-857ac5a933a4.png">

The "Other benchmarks" section will be fixed as we switch to `PerfherderGraphContainer` which Kyle is helping with.
