### ISSUE TITLE
Nimbledroid dashboard's "buzzfeed.com/daves4..." link reports "There has been a critical error."

### ISSUE THREAD

**Issue by cpeterso** [mozilla-frontend-infra/firefox-health-dashboard#134]
Clicking on the https://health.graphics/android/ dashboard's "buzzfeed.com/daves4..." link opens "https://health.graphics/android/graph?site=https://www.buzzfeed.com/daves4/the-new-york-times-makes-the-nerdiest-correction-e?utm_term=.tlL2KE08L6#.hwrBglaV2A" but that page shows an error instead of a Perfherder graph:
```
There has been a critical error. We have reported it. If the issue is not fixed within few hours please file an issue:
https://github.com/mozilla/firefox-health-dashboard/issues/new
```
Perhaps the buzzfeed.com URL does not match whatever URL Nimbledroid is testing?

**Comment by armenzg** [comment]
This has been fixed:
https://firefox-health-dashboard.netlify.com/android/graph?site=https://www.buzzfeed.com/daves4/the-new-york-times-makes-the-nerdiest-correction-e?utm_term=.tlL2KE08L6#.hwrBglaV2A
