### ISSUE TITLE
Get rid of flexboxes

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#157]
Too much dynamic resizing going on making it look bad on Chrome.

This is in reference to:
https://health.graphics/quantum/32
https://health.graphics/quantum/64

From one of our devtools folks:
"I don't see any reason to use flex on those full width rows"

**Comment by sakshi97** [comment]
Hi @armenzg !
I would like to take up this issue. Please give me a little more idea what needs to be done. Does the dynamic resizing need to removed altogether and which classes need to tackled specifically?
Also, on mobile view, the horizontal scroll-bar shows up but we lose some left-side part of the view altogether. Should I raise this as an issue?

**Comment by armenzg** [comment]
There's already an issue for the issues displaying on mobile.

Look at this file and see how many `display: flex` you can get rid of:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/index.css

Make sure that http://localhost:5000/quantum/64 looks well on Chrome by the end of it.

**Comment by armenzg** [comment]
I've decided that there's nothing inherently wrong with flex boxes.
We're going to redo the Quantum pages and we will make sure that everything plots properly.
