### ISSUE TITLE
Use code splitting to reduce build size

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#159]
index.acd3ce67.css   40.9 KiB       0  [emitted]         index
                       index.71000654.js   79.6 KiB       0  [emitted]         index
                          1.712a1e19.css   20.4 KiB       1  [emitted]
                           1.b93ad8ab.js   1.45 MiB       1  [emitted]  [big]
                     runtime.1ca11f96.js   1.46 KiB       2  [emitted]         runtime
                  index.acd3ce67.css.map   52.1 KiB       0  [emitted]         index
                   index.71000654.js.map    229 KiB       0  [emitted]         index
                      1.712a1e19.css.map   26.4 KiB       1  [emitted]
                       1.b93ad8ab.js.map   5.54 MiB       1  [emitted]
                 runtime.1ca11f96.js.map   7.76 KiB       2  [emitted]         runtime
                              index.html  433 bytes          [emitted]
                             favicon.ico    5.3 KiB          [emitted]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  1.b93ad8ab.js (1.45 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  index (1.59 MiB)
      runtime.1ca11f96.js
      1.712a1e19.css
      1.b93ad8ab.js
      index.acd3ce67.css
      index.71000654.js

WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

**Comment by armenzg** [comment]
Let's use `React.lazy` which was introduced in React v16.6.
https://reactjs.org/docs/code-splitting.html#reactlazy

For inspiration, you can look at how it's done in another repository https://github.com/taskcluster/taskcluster-web/pull/206.

**Comment by Shubhamchinda** [comment]
@armenzg Hey , Can I take this issue?

**Comment by klahnakoski** [comment]
@Shubhamchinda yes please!

**Comment by globefire** [comment]
@klahnakoski I would love to work on this issue if the work is inactive can you please assign it to me?

**Comment by armenzg** [comment]
Thanks @globefire! give it a try and once you have PR for it let us know.

**Comment by globefire** [comment]
Thank you @armenzg for giving me this opportunity.

**Comment by globefire** [comment]
@armenzg Can you guide me how should I get started?

**Comment by klahnakoski** [comment]
@globefire 

There are three charting libraries in this project.  Two of them have limited use; it would be nice to load them only if needed, or later:

* import TelemetryContainer from '../telemetry/graph';
* import MetricsGraphics from 'react-metrics-graphics';

Start with separating this page from the main build:

https://health.graphics/android/graph?site=https://www.google.com/

    <Route path="/android/graph" component={NimbledroidGraphPage} />

**Comment by the6thm0nth** [comment]
if this issue is wadering or @globefire is busy, can I try to resolve it?

**Comment by klahnakoski** [comment]
@the6thm0nth it appears @globefire  has disappeared.  Please have a try.  

Separating the page is still a good exercise, and would be gladly accepted.

**Comment by the6thm0nth** [comment]
@klahnakoski Thanks, I'll try in a few days.

**Comment by the6thm0nth** [comment]
> Let's use `React.lazy` which was introduced in React v16.6.
> https://reactjs.org/docs/code-splitting.html#reactlazy
> 
> For inspiration, you can look at how it's done in another repository [taskcluster/taskcluster-web#206](https://github.com/taskcluster/taskcluster-web/pull/206).

He suggested to use react-lazy, but this package use react 16.5 that is not react-lazy support version. is it ok to update react to 16.6 or should I try 3rd party library?

**Comment by the6thm0nth** [comment]
regardless of this issue, I've refactored a file while I'm trying code-splitting. May I send a pull request with this way?

https://github.com/the6thm0nth/firefox-health-dashboard/commit/7b81597d9564b8580680fa965d470a02ff6159e1

**Comment by klahnakoski** [comment]
@the6thm0nth  - Feel free up upgrade the packages if that helps you.  You may send pull requests, even broken ones (with `git push --no-verify`) so we can discuss the code specifically.

**Comment by HariShyamU** [comment]
Can I take this up if @the6thm0nth is busy?

**Comment by klahnakoski** [comment]
@HariShyamU   Yes, please. 

The blocker is the fact the telemetry charts are not showing.  You can see them here
 
    https://health.graphics/quantum/64

but not here (preview of same page)

    https://deploy-preview-574--firefox-health-dashboard.netlify.com/quantum/64

I believe the problem is @the6thm0nth was [trying to lazyload MetricsGraphics inside of graph.jsx](    https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/574/files#diff-4624072ebb6d0ddde8d37b9a48842ff7); since MetricsGraphics is NOT React friendly, graph.jsx must have considerable changes done to get it working.

The solution is to lazy-load graph.jsx; which is a React component. 

 Please merge off his branch and continue the work, that way @the6thm0nth can keep the credit for the work he did.

* fork this project
* clone your fork locally
* make a new branch
* merge @the6thm0nth's changes into your branch
    `git checkout -b the6thm0nth master`
    `git pull git://github.com/the6thm0nth/firefox-health-dashboard.git feature/code-splitting`
    `git checkout YOUR_BRANCH`
    `git merge the6thm0nth`
* do some fixes
* commit and push your changes
* make a PR for me to review

**Comment by HariShyamU** [comment]
@klahnakoski Sorry for the late response... So apart from lazy loading graph.jsx instead of MetricsGraphics, There's issue with MetricsGraphics not boding well with React. These two are the problems right?

**Comment by klahnakoski** [comment]
@HariShyamU It is the same issue: Lazy loading MetricsGraphics is hard because it is not a React component.  Lazy loading `graph.jsx` should be easy because it is a React component.  (be sure to use the graph.jsx found in master, not the (modified) version found in the6thm0nth).
