### ISSUE TITLE
Use Bugzilla's GraphQl instance for burndowns

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#160]
Codetribute uses an Apollo client to query information from the Bugzilla GraphQl instance we have:
https://github.com/mozilla-frontend-infra/codetribute/blob/master/codetribute-data-flow.png

Here's teh repo for the gateway:
https://github.com/mozilla-frontend-infra/bugzilla-graphql-gateway

We could then drop fetching from the backend.

**Comment by armenzg** [comment]
More info on the implementation:
https://github.com/mozilla-frontend-infra/codetribute/commit/c194fc96c9f6a92a901f6b5a0bb50ee667bedf2a

**Comment by klahnakoski** [comment]
We have a primitive jx-to-bugzilla-query tool:  https://github.com/mozilla/charts/blob/quantum-investigate/quantum/modevlib/Bugzilla.js#L177

**Comment by klahnakoski** [comment]
Fix: https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/462
