### ISSUE TITLE
Switch to Roboto font

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#177]
We've been using that font for all of the #frontend-infra projects.
Besides, I already included a Material UI widget that does not respect the default font (since I assume it should be set upo via a MUI theme that changes the font).

We need this dependency:
https://github.com/mozilla-frontend-infra/js-perf-dashboard/commit/37b569d439a38b901b2cbbf3fd003816032f0420#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R33
remove `Fire Sans` from package.json
and update `index.css`.

Don't forget to use `yarn add/remove <package_name>` rather than editing package.json directly.

**Comment by manasbedmutha98** [comment]
I would like to work on this issue. @armenzg , I hope you mean  the reference `"typeface-fira-sans": "^0.0.54"` for `Fire Sans`
Also, is it sufficient to replace all `Sans` with `Roboto` in this line? (I'm a beginner. Need help)
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/6de378a2ea355db270855e52d2c518fe2635bac8/src/index.css#L34
Or change this as well?
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/2936dd5e1d517d2af8ebf8c215580775ac6a9f8d/src/css/rhythm.css#L11

**Comment by armenzg** [comment]
Are you familiar to using Css? or the dev tools? (to inspect elements on the HTML page)

I suggest trying to make changes and see what changes.

**Comment by armenzg** [comment]
This is not a very hard issue. If you cannot provide a fix by tomorrow I will let other students give it a try. This is pre-Outreachy season and I cannot let easy issues sit unfinished. I hope you understand.

**Comment by manasbedmutha98** [comment]
Sorry I am stuck with exams. Anyone else who wants to have a go can please go ahead.
@armenzg Thanks for your patience till now.

**Comment by sakshi97** [comment]
Hi @armenzg . I would like to give this issue a try.

**Comment by armenzg** [comment]
Sure @sakshi97 !
Please ask review from @djmitche if you have the PR ready before Wednesday (I'm out until then)

**Comment by armenzg** [comment]
Thanks @sakshi97 @djmitche !
