### ISSUE TITLE
Adjust Redash graphs to drawn datasets close to the max value properly

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#178]
In this [page](https://deploy-preview-156--firefox-health-dashboard.netlify.com/android) (NOTE: Code yet to land) we can see that one of the lines goes to the top of the graph but it looks odd:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/44410/46832224-802a7780-cd73-11e8-9388-9ce452303b5c.png">

Here's the documentation:
http://www.chartjs.org/docs/latest/axes/cartesian/linear.html

If we pass a `max` value to the ticks larger that the highest value for that dataset we get to see the line properly drawn, however, the last two tick labels are too close:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/44410/46833794-9803fa80-cd77-11e8-87fb-c64cd0e7012a.png">

A `suggestedMax` of 31000 will extend the Y axis to 35000:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/44410/46833956-03e66300-cd78-11e8-8492-14e5de3ff24c.png">

We want a generic way to do this.

Here's a diff where I hardcoded the values:
```diff
armenzg@armenzg-mbp frontend$ git diff
diff --git a/src/containers/RedashContainer/index.jsx b/src/containers/RedashContainer/index.jsx
index 54debb4..8184562 100644
--- a/src/containers/RedashContainer/index.jsx
+++ b/src/containers/RedashContainer/index.jsx
@@ -30,6 +30,7 @@ const chartJsOptions = ({
         {
           ticks: {
             beginAtZero: true,
+            max: 31000,
             reverse,
           },
         },
```

**Comment by armenzg** [comment]
oh wow! I didn't know you could include a revision from GitHub.

I have a PR with your proposed fix and gave you credit in it.
Do you prefer to do the PR yourself so the code lands under your name?
Or are you OK if I land it?
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/180

**Comment by armenzg** [comment]
Also, let me know if you would be interested on contributing.

**Comment by kojole** [comment]
No problem if you merge #180.

**Comment by armenzg** [comment]
Thank you  @uu1t !
