### ISSUE TITLE
Customize graph tooltip

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#183]
Right now, if you visit https://health.graphics/android you will see the Telemetry section.

When you hover over any of those data points you will see a date with this format: `YYYY-MM-DD 00:00:00.000` and a score w/o the measurement (e.g. `ms`).
<img width="254" alt="image" src="https://user-images.githubusercontent.com/44410/46977814-24296100-d09b-11e8-9ef8-70161b8c0d6c.png">

I would like to drop the time from the tooltip and add the measuring unit.

The documentation to modify the tooltip is here:
https://www.chartjs.org/docs/latest/configuration/tooltip.html#external-custom-tooltips

**Comment by sakshi97** [comment]
Hey @djmitche . Can i take up this issue?

**Comment by djmitche** [comment]
Sure!

**Comment by armenzg** [comment]
I think you can make the changes asked for in here:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/utils/chartJs/redashFormatter.js#L16-L27

The RedashContainer (new component) is different than the TelemetryContainer (old component).

**Comment by aimenbatool** [comment]
Ahh! I reached here but it didn't make sense to me and I moved out of this file. Let me see again. Thanks.

**Comment by aimenbatool** [comment]
Hi @armenzg, Please look at the image below. I managed to remove the time from the tooltip by changing the format of time. But it applies to all charts. Which, I think isn't the requirement.
I added tooltipFormat key value [here](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/utils/chartJs/generateOptions.js#L15) to change the format of the tooltip.

You asked me to look [here](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/utils/chartJs/redashFormatter.js#L16-L27) , tried to update values of "submission_date" and "value" in '`datum`' before pushing into the `result[key].push(datum);` but it didn't work too. 
It is appearing rightly in console log but not in the graph. :-| 

![screenshot from 2018-12-12 20-28-09](https://user-images.githubusercontent.com/13648547/49881388-0df81100-fe50-11e8-876b-2b5b361ea4f9.png)

**Comment by armenzg** [comment]
Another approach would be to have `hour` be an optional value you include in `options`.
That way you can specify certain graphs to have certain format.

For reference this is the associated documentation:
https://www.chartjs.org/docs/latest/axes/cartesian/time.html
https://www.chartjs.org/docs/latest/axes/cartesian/time.html#time-units
https://www.chartjs.org/docs/latest/axes/cartesian/time.html#display-formats

You can also look in here for samples:
https://github.com/chartjs/Chart.js/tree/master/samples
