### ISSUE TITLE
Responsive dashboards for mobile

### ISSUE THREAD

**Issue by digitarald** [mozilla-frontend-infra/firefox-health-dashboard#2]
Make important data work on small screens.

**Comment by armenzg** [comment]
Once we [redo the Quantum pages](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/191) with the DashboardPage component.

This is not an issue for the Android view:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/44410/47309254-ec259f00-d601-11e8-9fbc-ff27fea21a25.png">

**Comment by armenzg** [comment]
No need to track.
We will redo the Quantum pages and we will make sure it works there.
