### ISSUE TITLE
Have internals use standard-name variables for chart things

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#209]
It would be nice to have some standard names for chart things ("axis", "series", etc) so we can remember less, and have some convention across multiple dashboards.  This also allows us to swap charting libraries; each charting library has a conversion method from our standard to theirs.

For example, here is my current standard: https://github.com/klahnakoski/MoDevMetrics/blob/dev/html/modevlib/charts/chartSchema.md  Which is in a directory containing conversion methods for CCC Charts and MetricsGraphics.

This conversion method already exists in the dashboard codebase here: https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/utils/chartJs/generateOptions.js  which takes a unique structure like:

```javascript
{
    "title": title,
    "scaleLabel": y_axis_label,
    "reverse": some_boolean_value
}
``` 

and converts it to chartJS standard, with some defaults. 

I suggest `<ChartJsWrapper>` be adjusted to accept standard chart parameters.  Instead of

```jsx
    <ChartJsWrapper
      title={name}
      type='line'
      height={80}
      options={generateOptions()}
      data={{
        datasets: data.map((part) => {
          return {
            data: part.map(({ datetime, value }) => {
              return {
                x: datetime,
                y: value,
              };
            }),
            label: name,
          };
        }),
      }}
    />
```

we have 

```jsx
    <ChartJsWrapper
      config={_.defaultsDeep(
        {
          title: name,
          area: {style: {height=80}},  //ALTERNATE 'area.style.height': 80
          data: data
          series: [{
            value: ["datetime", "value"], 
            type:"line", 
            label: name
          }]
        },
        generateOptions()  //MODIFIED TO EMIT STANDARD CHART PARAMETERS
      )}
    />
```

**Comment by armenzg** [comment]
Let me know when you want to tackle this and we can seat down and figure out what an initial version would look like.

**Comment by klahnakoski** [comment]
This would start with https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/200 : specifically, by naming the variable that controls the showing of zero from `options.reverse` to `axis.y.range.reversed` inside the dashboard code.  Also ensuing `axis.y.range.showZero` gets converted to `scales.yAxis.ticks.beginAtZero` inside of the `<ChartJsWrapper>`.

But first we need agreement on what we are heading toward so there is less surprise with variable renaming.

**Comment by armenzg** [comment]
This was brought into attention in here:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/256#discussion_r247529554

**Comment by klahnakoski** [comment]
Maybe the first coding step is to expand

**Comment by klahnakoski** [comment]
@karlht   this is the issue that is tracking the potential use of a pan-charting lib

**Comment by klahnakoski** [comment]
this has been started with https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/441 . As we use more "features", we will continue to use the `standard`, and/or update the `standard` so the data structure is documented
