### ISSUE TITLE
Sticky data points

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#211]
Make the data points be sticky when clicked,
Have the hg source link and revision/perf delta be sticky when clicked.

<img width="405" alt="image" src="https://user-images.githubusercontent.com/44410/43648647-0964dba4-9709-11e8-8e56-f46174a889a1.png">

**Comment by armenzg** [comment]
@asingh217 if you can't get to this we will finish it up and give you credit for the original PR:
https://github.com/mozilla-frontend-infra/firefox-performance-dashboard/pull/104

Works for you?

I hope you're doing better.

**Comment by aimenbatool** [comment]
@armenzg, @sarah-clements It looks like this issue is from JS Perf Dashboard. Am I suppose to go in that project and complete it or the same thing needs to be implemented here in this project? 
If yes, then where?

**Comment by armenzg** [comment]
We just need to complete it in this project.

Try to look for similar components from that PR on this project.
The components might even be named the same.
