### ISSUE TITLE
Enhanced data when hovering over data points

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#213]
Add the hg source link and revision/perf delta.

<img width="405" alt="image" src="https://user-images.githubusercontent.com/44410/43648647-0964dba4-9709-11e8-8e56-f46174a889a1.png">

**Comment by armenzg** [comment]
@aimenbatool right now when hovering data points we get this:
<img width="187" alt="image" src="https://user-images.githubusercontent.com/44410/50095769-35e6cc00-01e4-11e9-9770-9700af44af88.png">

Instead we would like to see more meta data.

When you visit Perfherder (follow the hyperlink icon):
<img width="153" alt="image" src="https://user-images.githubusercontent.com/44410/50095920-84946600-01e4-11e9-837f-c1c455118644.png">
you will get to this page:
https://treeherder.mozilla.org/perf.html#/graphs?series=mozilla-central,1776360,1,10&series=mozilla-central,1775979,1,10&series=mozilla-central,1776166,1,10&selected=mozilla-central,1776166,413555,667080523,10

If you click on that same data point as on my 1st screenshot on this comment you will see the following:
<img width="291" alt="image" src="https://user-images.githubusercontent.com/44410/50096027-c9200180-01e4-11e9-9270-bc48c1d5ae82.png">

For now, pick one piece of metadata you believe you could add to PerfherderGraphContainer.
For instance, the delta between the last data point and the current one.

You can also see the metadata associated to a data point [1]: (look for `663428682`):
https://treeherder.mozilla.org/api/project/mozilla-central/performance/data/?framework=10&interval=1209600&signature_id=1775979

The push ID will then lead us to:
https://treeherder.mozilla.org/api/project/mozilla-central/resultset/412032/
On that response you will see that most recent revision for that push is `336f58aeb663c01ede2a646d51d5015bf741538d` which is used when building this link:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=ca0f00593e38cdab54c3a990059bbf1150e77365&tochange=336f58aeb663c01ede2a646d51d5015bf741538d

Now, you may wonder where `ca0f00593e38cdab54c3a990059bbf1150e77365` comes from?
If we look at the Perfherder data [3] we will see that the last data point prior to 412032 is 411945 which leads us to:
https://treeherder.mozilla.org/api/project/mozilla-central/resultset/411945/
which gives us `ca0f00593e38cdab54c3a990059bbf1150e77365`

Notice on [1] we have the `job_id` which allows us to build this link:
https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&revision=ca0f00593e38cdab54c3a990059bbf1150e77365&selectedJob=216000218&group_state=expanded

Now, don't go all out and try to add *all* metadata. Let's start with one or the ones that are most easy to figure out and we can follow up in the future with more.

[1]
```json
      {
            "value": 21.49,
            "push_id": 412032,
            "signature_id": 1775979,
            "push_timestamp": 1544262484,
            "job_id": 216034625,
            "id": 663428682
        },
```
[2]
```json
{
    "id": 412032,
    "revision": "336f58aeb663c01ede2a646d51d5015bf741538d",
```
[3]
```json
{
            "value": 21.63,
            "push_id": 411945,
            "signature_id": 1775979,
            "push_timestamp": 1544218833,
            "job_id": 216000218,
            "id": 663268071
        },
```

**Comment by aimenbatool** [comment]
Here is what I did to figure out the solution.
I console.log(new Data) [here](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/utils/perfherder/chartJs/getPerfherderData.js#L27)

And here is what I received. (I have mentioned things on the screenshot). [1]

I have got some idea of the comments you wrote above, as I followed the steps multiple times, but still confused. 

Question is: 

> If you click on that same data point as on my 1st screenshot on this comment you will see the following: [Image](https://user-images.githubusercontent.com/44410/50096027-c9200180-01e4-11e9-9270-bc48c1d5ae82.png)

It looks like that meta is already generated and i available on perfherder for example the value of Delta.  How am going to get this data? Or it is generating on run time? 

[1]
<img width="1649" alt="screen shot 2018-12-19 at 10 05 07 pm" src="https://user-images.githubusercontent.com/13648547/50236237-b9b6d900-03db-11e9-906a-a5e47900e1b4.png">

**Comment by armenzg** [comment]
Don't get confused about the 'meta' object. There's a library we use called `perf-goggles`. It adds that 'meta' object to simply describe the associated data. I tend to always return a meta object when I have some data. It's as if you hit an API that would return data + a description of itself.

You need to calculate the delta value by iterating through all data points by recency.
You need to look at the previous data point and the current data point to calculate the delta.

**Comment by armenzg** [comment]
I incorrectly closed this issue when there's a lot more metadata we need to add.
My apologies!

**Comment by aimenbatool** [comment]
Can you please name a few metadata so will look into it sometime later.

**Comment by armenzg** [comment]
Given this:
<img width="405" alt="image" src="https://user-images.githubusercontent.com/44410/43648647-0964dba4-9709-11e8-8e56-f46174a889a1.png">
and this:
<img width="291" alt="image" src="https://user-images.githubusercontent.com/44410/50096027-c9200180-01e4-11e9-9270-bc48c1d5ae82.png">
and compared to this:
<img width="178" alt="image" src="https://user-images.githubusercontent.com/44410/50705188-f7487280-1027-11e9-960c-dbfc18b9fa49.png">

If you want we can break this issue into multiple ones were each one would add one of these:

- Change the delta to be `+/-X (+/-Y %)`
- Add hyperlink to Hg (e.g. [d2bc993e14ea](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=b243a5a3fc646329ca5b5d169f7fe2f16dfb56eb&tochange=d2bc993e14ea1384c2d9b80cca098b48eb19948a))
- Add link to [job](https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&revision=d2bc993e14ea1384c2d9b80cca098b48eb19948a&selectedJob=218727119&group_state=expanded)
- Add link to [compare](https://treeherder.mozilla.org/perf.html#/comparesubtest?originalProject=mozilla-central&newProject=mozilla-central&originalRevision=b243a5a3fc646329ca5b5d169f7fe2f16dfb56eb&newRevision=d2bc993e14ea1384c2d9b80cca098b48eb19948a&originalSignature=778e915655873cccaafa2d8c495f7b51306ce251&newSignature=778e915655873cccaafa2d8c495f7b51306ce251&framework=10)
- Indicate if "higher is better" or "lower is better"

Most of the metadata is described in here:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/213#issuecomment-447908593

**Comment by djmitche** [comment]
The percents would, I think, be the percent change from the previous datapoint.  So given previous value P and current value C, the percentage change is `(C / P * 100) - 100`.  For example, if P was 300 and C is 330, the percentage change is 10%

**Comment by djmitche** [comment]
that's equivalent :)

**Comment by aimenbatool** [comment]
@sarah-clements , @djmitche 
This issue is 99% done except **adding anchor inside a callback**. I tried a few solutions in the past days while working on other issues but no success. 

[This answer](https://stackoverflow.com/a/42095510/5864458) states that callbacks don't allow HTML tags and we can use a custom tooltip. But in our case, we are unable to use a custom tooltip as well because we need to add data in the footer and it is not working inside it. I tried doing it. 

I posted a question at [stackoverflow](https://stackoverflow.com/questions/54655686/how-to-add-html-tags-inside-chartjs-callback-footer-function) to get a better answer. 

In this issue we required to add: 

- Change in Value (delta)
- Percentage Change
- Indicator of higher or lowe
- Job link
- Hg Link

first three are working fine, we hv last two links also but unable to display the anchor. 

Should we add first three things and do remaining two in follow up PR till I find some better solution?

Whatever you suggest.

**Comment by aimenbatool** [comment]
### Update on what's done and what needs to be done. 

Most of the metadata has been added in this PR https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/268 

Only Job Link and Hg Link is left, we are able to generate the link based on the given information but chartjs callback doesn't let us add HTML tags inside it so we are unable to make it a working link. 

Read this https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/213#issuecomment-462891912 for a better understanding. 

I have created [this gist](https://gist.github.com/aimenbatool/add2590967f15ef4dc9a6982710aa304#file-perfherderformatter-js-L19-L51) for better idea of where we left doing it. 

An issue https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/303 has been created for the remaining part of this issue.

Thanks!
