### ISSUE TITLE
Transfer FxPerfDashboard into FxHealthDashboard

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#214]
There's some duplicated code between the two projects and it will be easier to maintain them if they're under the same project.

**Comment by aimenbatool** [comment]
@armenzg  Please provide more information on it.

**Comment by armenzg** [comment]
I will work a bit more on this PR and land it:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/231

This will be the view will be adding to:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/61a862f9b8907368af23187880f5ea70c23a3408/src/views/JsTeam/index.jsx

To begin with, simply try to reimplement this page w/o *working* pickers and without *working* drilldowns:
https://arewefastyet.com/win10/overview?numDays=60
I say *working* because you can copy/paste the code as in the original project and we can iterate little by little to make it fully functional.

This PR will take several iterations.

[1] Pickers
<img width="329" alt="image" src="https://user-images.githubusercontent.com/44410/50101242-4ef57a00-01f0-11e9-836a-54b1689b6031.png">

[2] Link to Perfherder and link to drilldown (aka more details view)
<img width="151" alt="image" src="https://user-images.githubusercontent.com/44410/50101375-8d8b3480-01f0-11e9-812f-d69d09ef6332.png">

**Comment by klahnakoski** [comment]
this may be easier now with https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/313

**Comment by klahnakoski** [comment]
The navigation components have been copied over.  Specific series can be requested with a new issue
