### ISSUE TITLE
Show Perfherder alerts on graphs

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#215]
This is something that will be needed to get the DevTools dashboard moved in here.

Link to their dashboard:
https://firefox-dev.tools/performance-dashboard/

They currently annotate regressions/improvements via a Google Doc:
<img width="308" alt="image" src="https://user-images.githubusercontent.com/44410/49614821-79863e00-f979-11e8-965e-2b440a38c166.png">

**Comment by armenzg** [comment]
there are performance alerts that sheriffs report and there are APIs to check for them https://treeherder.mozilla.org/docs/#performance-alert-list
10:36 arno__: if you load this https://treeherder.mozilla.org/perf.html#/graphs?series=mozilla-central,1762616,1,10
10:36 you can see in the network pane that it queries https://treeherder.mozilla.org/api/performance/alertsummary/?alerts__series_signature=1762616&repository=1
10:37 if there was an alert, some of the dots in the graph would be drawn differently

**Comment by arnold-iakab** [comment]
Since alerts are being reported only for inbound and autoland, how to we map them in our graphs considering that Health Dashboard queries data from mozilla-central?

**Comment by armenzg** [comment]
In that case this issue does not apply.
Thanks for checking!
