### ISSUE TITLE
Create view to plot any Perfherder series you want

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#217]
Similar to:
https://treeherder.mozilla.org/perf.html
but let's focus on one single dataset.

This will be a good page to let people try adding data before modifying the Quantum page directly.
Eventually we might make something better but for now it will be sufficient.

**Comment by klahnakoski** [comment]
We may want to let the user declare a filter on some number of series properties.  https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/311

**Comment by klahnakoski** [comment]
It is probably best to copy a current page/component and change the query that drives it.
