### ISSUE TITLE
Change perf drilldowns to use PerfherderGraphContainer

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#218]
This kind of route: https://health.graphics/quantum/windows10-64/motionmark_htmlsuite
Current look [1]
Expected look (not all details on that screenshot; mainly the graphs)[2]

Kyle was currently looking into this.
This is part of Redo Quantum pages milestone.

[1]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/44410/49620406-b9a3eb80-f98e-11e8-9998-ad3a20465eb1.png">
[2]
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/44410/49620425-ce807f00-f98e-11e8-9a81-272b3086d7f9.png">

**Comment by klahnakoski** [comment]
Done some time ago:
https://health.graphics/windows/subtests?suite=MotionMark+HTML&platform=win64&past=month&ending=2020-01-21
