### ISSUE TITLE
TelemetryContainer not to use fx-health-backend

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#219]
Currently a TelemetryContainer [1][2][3][4] will fetch the data via the firefox-health-backend.

The code path for hitting the backend is:
https://github.com/mozilla/firefox-health-backend/blob/master/src/perf.js#L111-L116
which calls `fetchTelemetryEvolution`:
https://github.com/mozilla/firefox-health-backend/blob/master/src/perf/tmo-wrapper.js
which calls `getEvolution` from:
https://github.com/mozilla/firefox-health-backend/blob/master/src/perf/tmo-wrapper.js

We can probably drop those two files under src/utils/telemetry and remove some of the code that would not apply to frontend code (e.g. `ctx.body` code).

[1]
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/quantum/index-64bit.js#L407-L412
[2]
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/telemetry/graph.js
[3]
https://firefox-health-backend.herokuapp.com/api/perf/telemetry?architecture=x86-64&name=winOpen
[4]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/44410/49620477-11425700-f98f-11e8-923c-dd86f38e814b.png">

**Comment by klahnakoski** [comment]
We are making a copy of the perf data in BigQuery.  Maybe we can do the same for this information
