### ISSUE TITLE
TelemetryContainer to use ChartJsWrapper instead of metrics-graphics

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#220]
We would not need the following code:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/telemetry/graph.js#L29-L55
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/telemetry/graph.js#L24-L26

Remove the usage of `ref={div => this.graphSubtitleEl = div}`
replace this block for <ChartJsWrapper>:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/telemetry/graph.js#L66-L69
and transform the data we receive from the backend to fit the needs of ChartJs:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/telemetry/graph.js#L19-L20

**Comment by aimenbatool** [comment]
Hi @armenzg! 

These links aren't working. Can you please share more information about this issue?

**Comment by armenzg** [comment]
Hi @aimenbatool 
All of the graphs in the Quantum pages use a component [1] that query the Telemetry data source via the Firefox Health backend [2].

That component also uses react-metrics-graphics rather than ChartJsWrapper.
In order to only have one charting library, we should look into making a new component that plots the Telemetry data via ChartJsWrapper.

On a future issue, we could focus on making the component query the Telemetry data source directly rather than via the backend.

Does this help?

[1]
<img width="329" alt="image" src="https://user-images.githubusercontent.com/44410/54607877-d2a84800-4a25-11e9-8132-7f8c3867941e.png">
[2]
https://firefox-health-backend.herokuapp.com/api/perf/telemetry?architecture=x86-64&name=tabSwitch

**Comment by aimenbatool** [comment]
I got it. Thanks!

**Comment by klahnakoski** [comment]
This will not happen.  First, the telemetry presentation code has been split out so it does not impace pages that do not need it.  Second, we will replace the frontend when/if https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/219  is done
