### ISSUE TITLE
Add ability to configure PerfherderGraphContainer with disabled series

### ISSUE THREAD

**Issue by jmaher** [mozilla-frontend-infra/firefox-health-dashboard#224]
we currently run raptor on linux64-qr and windows10-qr so we should be able to compare a given benchmark (i.e. speedometer) between firefox && firefox-qr, likewise the existing firefox vs chrome.

This is a bit vague, ideally there is a good idea for how to do this either on the existing graphs, or a secondary page.

**Comment by armenzg** [comment]
There's some docs here:
https://www.chartjs.org/docs/latest/developers/updates.html

**Comment by aimenbatool** [comment]
@sarah-clements can you please explain a bit?

**Comment by klahnakoski** [comment]
@jmaher I think we are in a position to add *qr as yet-another-platform to the config files.  I will try to keep this in mind when adding fenix

**Comment by jmaher** [comment]
thanks @klahnakoski .  As a note, Fenix doesn't have *qr, that is only desktop.  It sounds like we are getting closer to having a front end that can do many comparisons.

**Comment by klahnakoski** [comment]
when we have a specific chart that needs this, then we will add it.
