### ISSUE TITLE
small tweaks to tp6 sub metrics view

### ISSUE THREAD

**Issue by jmaher** [mozilla-frontend-infra/firefox-health-dashboard#227]
(Edited comment)

https://arewefastyet.com/win10/tp6-facebook?numDays=60

1) "all subbenchmarks" -> does not open all subbenchmarks
2) if there is not enough data for a specific metric, ensure dates align across all metrics
4) add in google chrome (issues as we don't have identical metrics to record)

**Comment by klahnakoski** [comment]
@jmaher   I am closing this because it belongs to arewefastyet, OR the current tp6 view on the health dashboard is good enough.
