### ISSUE TITLE
Do not further requests when changing the timeRange

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#228]
We're adding the ability to set the range of data to show with a 'Time range' picker:
#84

The way this is implemented is by requesting the data again from Perfherder.

We should change this so we fetch all data for the year and manipulate the data in the UI to refresh the graphs.

It should be a good idea to review this section:
https://www.chartjs.org/docs/latest/developers/updates.html

**Comment by klahnakoski** [comment]
done
