### ISSUE TITLE
use zilla slab font

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#235]
Maybe we should use this font on the dashboards:

https://github.com/mozilla/zilla-slab/releases/tag/v1.0

**Comment by armenzg** [comment]
That font is more the official Mozilla sites.
At #frontend-infra we are sticking with Roboto to keep consistency across tools.

If you want, you can bring it up on https://groups.google.com/forum/#!forum/mozilla.dev.webdev
and we can point folks there for the discussion.
