### ISSUE TITLE
Report travis build sizes for each PR

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#239]
It may be nice to have each PR report the change in the main application size ([today it happens to be `assets/1.c9f24ee3.js`](https://travis-ci.org/mozilla-frontend-infra/firefox-health-dashboard/jobs/470172054#L512).  This would allow us to balance the size of the new code with it's utility.

**Comment by armenzg** [comment]
Maybe this?
https://github.com/siddharthkp/bundlesize

This would also help issue #159 

Whatever splitting solution we use we need to make sure it does not break HMR.
It happened to me with `react-loadable`:
https://github.com/mozilla/bugzilla-dashboard/commit/626af8c429e6188eda3801e624f5a8161a51a3ab

**Comment by klahnakoski** [comment]
I would still like to see this done

**Comment by jaskeerat789** [comment]
Can I work on this @klahnakoski ?

**Comment by klahnakoski** [comment]
@jaskeerat789 Yes please.

**Comment by jaskeerat789** [comment]
@klahnakoski thanks for the permission, can you provide me with more details.
I saw @armenzg 's comment and the package bundlesize seems good to me.

**Comment by noi5e** [comment]
@jaskeerat789 are you still working on this issue? if not, i'm happy to take a look.

@klahnakoski i'm with Outreachy, looks like the other applicants claimed the other "good first issues." let me know if there's one in particular you think would be good for a new contributor.

**Comment by kimberlythegeek** [comment]
Hi @noi5e ! I am the other mentor for the Outreachy project--feel free to reach out with any questions you may have, as well as request code reviews from me.

I realize there are not many open issues for this dashboard, but you can also make contributions to Perfherder, another react dashboard. This is outside the scope of the internship, but there are many more issues available to work on.

https://bugzilla.mozilla.org/buglist.cgi?product=Tree%20Management&component=Perfherder&resolution=---&list_id=15132483

**Comment by SaumyaSinghal** [comment]
Hello @kimberlythegeek Can i be assigned this issue if no one else is working on it?

**Comment by kimberlythegeek** [comment]
@SaumyaSinghal Yes 🙂 please reach out if you have any questions!

**Comment by SaumyaSinghal** [comment]
Thanks @kimberlythegeek. Can you please help me on how to get started with this issue?

**Comment by kimberlythegeek** [comment]
@SaumyaSinghal Armen suggested a library in a previous comment, which looks promising. Have you looked into that one?

**Comment by SaumyaSinghal** [comment]
Yes @kimberlythegeek that seems pretty good to me!
