### ISSUE TITLE
Add link to new TP6 page

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#245]
Once the TP6 page is added, linking to it will help humans navigate to it.

Maybe linking from the quantum pages is best. https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/241#pullrequestreview-188724874  Some context around that link will help.

**Comment by armenzg** [comment]
I think under the quantum page itself would make more sense. I'm open to both options.

**Comment by klahnakoski** [comment]
Yes, I should have asked this question of Vicky. I will put it in the index-64bit.js PR.
