### ISSUE TITLE
Nimbledroid:  include a comparison with a current WebView

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#248]
as well, as that will be relevant for some deliveries (notably Amazon)

![image](https://user-images.githubusercontent.com/2334429/50649981-42418780-0f4d-11e9-8125-c38d23ec3c73.png)

**Comment by armenzg** [comment]
Who requested this? Where is the WebView data coming from?
We have limits on number of scenarios & number of apps with our current contract with Nimbledroid.

**Comment by klahnakoski** [comment]
fixed, ready for when new data arrives.
