### ISSUE TITLE
Show performance regressions breakdown for Firefox versions

### ISSUE THREAD

**Issue by davehunt** [mozilla-frontend-infra/firefox-health-dashboard#260]
I'd like to see the number of open performance regressions for each Firefox version in development. We currently have meta bugs such as [bug 1513237](https://bugzilla.mozilla.org/show_bug.cgi?id=1513237) for this, but I'd like to use other bug attributes to create this summary with links to Bugzilla. We could use the *perf*, and *regression* keywords in combination with the *status-firefox* fields, however these don't appear to be used consistently. For example [this search](https://bugzilla.mozilla.org/buglist.cgi?keywords=perf%2C%20regression&f1=cf_status_firefox66&keywords_type=allwords&list_id=14509750&o1=equals&resolution=---&query_format=advanced&v1=affected) currently returns four results, whereas there are seven open dependencies for [bug 1513237](https://bugzilla.mozilla.org/show_bug.cgi?id=1513237). What do you think @klahnakoski?

**Comment by armenzg** [comment]
This query would show all 7 bugs blocking 1513237:
https://bugzilla.mozilla.org/buglist.cgi?list_id=14511382&o1=equals&v1=1513237&f1=blocked&resolution=---&query_format=advanced

The code to show any plots is document and it's pretty simple:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard#bugzillaburndown

```javascript
<BugzillaBurndown
  queries={[
    {
      label: 'Open Fx66 perf bugs',
      parameters: {
        blocks: '1513237',
        resolution: '---',
      },
    },
  ]}
  title='Firefox 66 performance issues'
/>
```
You can easily test it locally.

I've deployed a sample deployment:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/261
https://deploy-preview-261--firefox-health-dashboard.netlify.com/js-team
<img width="613" alt="image" src="https://user-images.githubusercontent.com/44410/51122700-6a9c7200-17e8-11e9-9525-8b3ccd4b7436.png">

FYI there's potentially some improvements to that code to not require `BugzillaUrlContainer`.

**Comment by klahnakoski** [comment]
@davehunt 

What gets shown depends on the process you are looking to establish, or what people are currently need. 

We currently have https://charts.mozilla.org/quantum/p1.html which is showing p1 bugs.  A request from jgong is to have it show mulitple versions.  The rules can be changed to show any category of bugs you would like.

There is also a Bug Counter, but it is pointing to the old cluster of bugs, so is busted.  I will put the link here with hope I fix it later today:  https://charts.mozilla.org/metrics/Bug-Counts.html

These dashboards, and others like it, should be re-created using React

**Comment by davehunt** [comment]
Thanks, I think the quantum p1 dashboard is the best place for this information.
