### ISSUE TITLE
turn off the inertia on chart lines

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#262]
The line charts have some Bezier, or inertial,  component that is misleading.  Change charts to show scatter plots, if not show straight lines.

![image](https://user-images.githubusercontent.com/2334429/51133089-fbcc1280-1801-11e9-99ab-be4e601a752c.png)

**Comment by djmitche** [comment]
I think I used that chart on a middle-school math test once: which one of these is NOT a graph?  (Correct answer this one)
