### ISSUE TITLE
Show individual measures, not the geomean?

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#270]
the tp6 ages show the geo-mean of some measures; these are not necessarily the same set for any given page: they are not comparable.  Change the page to show page load time, including an option to select any of the other measures being collected, if they exist.

**Comment by klahnakoski** [comment]
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/313

**Comment by smaug----** [comment]
So Load Time means now what?
