### ISSUE TITLE
Graph for nimbledroid fluctate without valid data point

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-frontend-infra/firefox-health-dashboard#275]
https://health.graphics/android/graph?site=https://people.com/amp-stories/royal-a-to-z

Looking at this graph, the geckoview Example app shows quite a fluctuation.  But looking at the data points, there are no data points for the higher values.  it should more or less a straight line.  This graph misleads viewers to think that there is a wild swing on the pageload data.

**Comment by klahnakoski** [comment]
It appears two "customFlow"s are mapping to the same URL

    customFlow123 (https://people.com/amp-stories/royal-a-to-z/)
    customFlow124 (https://people.com/amp-stories/royal-a-to-z)

Looking at the live URLs, one had cover page for the royal family, but after the first load, it started showing 404.
