### ISSUE TITLE
Nimbledroid comparisons should compare chrome vs geckoview example

### ISSUE THREAD

**Issue by stuartphilp** [mozilla-frontend-infra/firefox-health-dashboard#276]
As Focus updates are not reliable/fast we should switch the Nimbledroid target comparison to be geckoviewExamplePageLoadTime / ChromeBetaPageLoadTime

I believe it's just https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/utils/nimbledroid/index.jsx#L114

**Comment by stuartphilp** [comment]
We should do the cold startup graph as well (remove org.mozilla.klar and replace with reference browser, I've filed #277 for that), but what I'm referring to here is the detailed view and the individual page graphs

![screen shot 2019-01-29 at 9 02 43 am](https://user-images.githubusercontent.com/2964961/51913588-d95efb00-23a4-11e9-9220-65e0eca3b3dc.png)

"Geckoview" is the Focus/Klar app in this case, which we don't want to compare. We want Example app vs Chrome (because the Example app has nightly Geckoview builds in it so we can see the latest improvements)

**Comment by klahnakoski** [comment]
finally,  https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/290

**Comment by klahnakoski** [comment]
![image](https://user-images.githubusercontent.com/2334429/52285788-00817380-2935-11e9-9039-dd244468623b.png)

**Comment by klahnakoski** [comment]
saw mistakes as I posted the last image:

![image](https://user-images.githubusercontent.com/2334429/52286533-5d315e00-2936-11e9-83a2-b546f8e72ec7.png)

**Comment by klahnakoski** [comment]
@stuartphilp please close this when you have confirmed these PRs fixed the issue.
