### ISSUE TITLE
add another column to compare fenix against chrome

### ISSUE THREAD

**Issue by stuartphilp** [mozilla-frontend-infra/firefox-health-dashboard#277]
Focus should be replaced with the Reference Browser on the Nimbledroid charts. r-b has tracking protection on by default, while geckoview example has tp off. 

We should include another column to compare r-b vs chrome so we can see both tp on and off. 

The columns should be:
URL - reference browser score - gv example score - chrome beta score - gv example vs chrome beta (tp off) - reference browser vs chrome beta (tp on)

GV example vs Chrome Beta will still be the target for highlighting.

**Comment by stuartphilp** [comment]
correction, the request is to replace BOTH focus and gv example with reference browser and then toggle tp on and off. so r-b tp on, r-b tp off, chrome beta. and then compare for highlights to r-b tp off

**Comment by klahnakoski** [comment]
@stuartphilp  Where is the Reference Browser data coming from?  The Nimbledroid service endpoint?  You have links to that?

**Comment by stuartphilp** [comment]
Coordinate with @npark-mozilla  - he is looking at adding r-b to nimbledroid

**Comment by klahnakoski** [comment]
change this to: add another column to compare fenix against chrome

**Comment by klahnakoski** [comment]
Solution?  https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/423

**Comment by klahnakoski** [comment]
done
