### ISSUE TITLE
Update netlify.toml with recent yarn version

### ISSUE THREAD

**Issue by sarah-clements** [mozilla-frontend-infra/firefox-health-dashboard#283]
It looks like new linting changes being made in #279 are failing because of a yarn version mismatch between the travis.yaml and netlify.toml file, [see comment](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/279#issuecomment-459001001) per @eliperelman. @helfi92 can you please make this change and also give @aimenbatool read access to the logs?

**Comment by eliperelman** [comment]
The netlify.toml changes can be made by anyone which should unblock this against #279.

**Comment by helfi92** [comment]
> The engine "yarn" is incompatible with this module. Expected version ">=1.10.1".

To remove this error, add the following section to `netlify.toml`:

```
[build.environment]
  YARN_VERSION = "1.10.1"
```
 
We do a similar thing in https://github.com/taskcluster/taskcluster/blob/ce2f069688a5042716bdd487383871bbafc49a11/netlify.toml#L8.

**Comment by helfi92** [comment]
> give @aimenbatool read access to the logs

I sent an invitation to s.aimenbatool@gmail.com :)
