### ISSUE TITLE
Discussion: The nimblegraph complexity

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#288]
Navigating the nimblegraph components is a nightmare. My IDE lets me jump around the definitions fine, but the browser debuggers are primitive; forcing me to recall the locations of each of the React components so I can set break points. Stepping into code does not work because react has inserted multiple functions between every nimbledroid function.

Here is a diagram that demonstrated the problem:

![image](https://user-images.githubusercontent.com/2334429/52220934-06605180-286e-11e9-92f7-7af43d6a1159.png)

Arrows show dependencies, and only the dependencies exclusive to the nimbledroid code (libraries and config needed by other components are not included for simplicity).

There are some problems I see:
* A nimbledroid components are spread over multiple directories, making it near-impossible to reuse in another dashboard.
* The `components` are used by just one `container`; they should be in-lined, or at least kept in the container file.
* `BackendClient` is some attempt at isolation, but it is only used by nimbledroid so it only serves to disperse the data fetching logic
* `utils/nimbledroid/index.jsx` is not a component, rather some configuration plus some data transformation logic. It should be merged with `fetchNimbledroidData`
* There are multiple directories with a single `index.jsx`:  I do not know why this pattern exists, but it makes browser debug navigation just a bit more painful.

These problems are repeated over the whole of the project, and I would like to clean it up, over time, as we touch each piece of code (if ever).  I would like to use the following principal 

> Only use indirection if more than one component/method/object must reference it.

This means we should not be making `index.jsx` files unless we need another file in the same directory.  We should not make component files when only one component file needs the component, we should consider in lining components if the component is used in only one place. Methods should be in-lined if used by only one method, files should be combined if used by only one other file. 

But first, @eliperelman, @sarah-clements, @aimenbatool, I would like all your input.

**Comment by sarah-clements** [comment]
>  We should not make component files when only one component file needs the component, we should consider in lining components if the component is used in only one place.

I'll admit I'm not as familiar with the code base but I think potential problems with adopting this approach is that files could become unwieldy if all of a parent component's child components were in the same file. It would also make it difficult to see what components can be reused elsewhere. In the Treeherder codebase, we generally put one component to a file and generic, shared components go in a ./shared directory (as do helper functions, depending on if they're used elsewhere in the app or only by one particular app - TH, Perfherder, Intermittent Failures View).

Putting multiple pure (stateless) components per file might be a good compromise if they are grouped together logically and the file name is clear.

> Methods should be in-lined if used by only one method
Yes, this makes sense. If a method is only used by one component, no need to put it into a generic helper file to start (unless it is so generic it would obviously be reused, like generating urls).

**Comment by klahnakoski** [comment]
>  files could become unwieldy if all of a parent component's child components were in the same file.

Yes, if the file becomes enormous, then it can be broken up, but only as files in one directory, not 10 directories. 

> It would also make it difficult to see what components can be reused elsewhere. In the Treeherder codebase, we generally put one component to a file

Treeherder is an OLTP program.  This project and dashboards in general, are OLAP programs. These have very different usage patterns, and very different lifespans. The Treeherder codebase would benefit from finding opportunities to reuse code because it lives long and is big.  Dashboards do not live long because business changes focus and needs evolve. Dashboard code should be written fast, and treated as disposable.  For example, `src/components/StatusWidget/Title.jsx` is never getting reused; it is unlikely to be a good fit for another component, and even if it is, it is easier to rewrite than find-and-reuse. 

That said, even in the OLTP case, I also do not have a problem with separate modules duplicating functionality; reducing common dependencies can make it easier to reuse the module, and retire code that is no longer used.

I do agree that dashboards, require a common suite of tools, like Treeherder's `./shared directory;  but since dashboards are disposable, this shared code belongs in a longer-lived repo. This is why I would like to start accumulating code for it; Perfherder's React effort will probably share tools in common with other dashboards found around our department. https://docs.google.com/document/d/1WMp3Az5m0ystbYODjHKa7MCYLSZt9JIWfA1VB9SizP8/edit

**Comment by sarah-clements** [comment]
> I do agree that dashboards, require a common suite of tools, like Treeherder's `./shared` directory; but since dashboards are disposable, this shared code belongs in a longer-lived repo. This is why I would like to start accumulating code for it; Perfherder's React effort will probably share tools in common with other dashboards found around our department. https://docs.google.com/document/d/1WMp3Az5m0ystbYODjHKa7MCYLSZt9JIWfA1VB9SizP8/edit

When you refer to a longer-lived repo, are you referring to creating components that handle the boilerplate of say, a reactstrap dropdown menu (or Material Design equivalent) like [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/introduction.md)? Is the goal to create a consistent UI across all Moz dashboards?

With regards to Perfherder, anything beyond additional graph functionality (as a layer on chartJS) I'm not seeing the relevance of putting into a library. The collection of tables for the compare view and the modal for the graphs tab are very specifically tailored to Perfherder's needs. If another dashboard needed to replicate all of that functionality exactly, why not just redirect to Perfherder to begin with?

Maybe I need to see a few examples to see what you're getting at.

**Comment by klahnakoski** [comment]
Yes, that layer on top of chartsJS might be reusable. I have no idea how to "whip up" a functional drop down menu: So that can be included too. The compare view will use some delta bar charts: Include those.

Other things, either built of found, like:

* Widgets for selecting URL parameters
* Widgets for raising errors to users 
  * [criticalErrorMessage](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/d8722ec8eb80c4a74bae3e7f5f1846f0b4085957/src/components/criticalErrorMessage.jsx)
  * [genericErrorBoundary](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/d8722ec8eb80c4a74bae3e7f5f1846f0b4085957/src/components/genericErrorBoundary.jsx)
* Neutrino - so a whole React app can be setup quickly
* a logging library - both to deliver problems to a server, and show reasonable errors to user
* data extractors - like, something to help compose complicated Bugzilla's queries
* A standard data format to communicate with more than one chart library: https://github.com/klahnakoski/MoDevMetrics/blob/dev/html/modevlib/charts/chartSchema.md
* Frontend authentication code
* Some vector library so we can do data transformation and analysis on the client side.

**Comment by sarah-clements** [comment]
> Yes, that layer on top of chartsJS might be reusable. I have no idea how to "whip up" a functional drop down menu: So that can be included too. 

[This](https://reactstrap.github.io/components/dropdowns/) is what I mean by creating a dropdown menu and [this](https://github.com/mozilla/treeherder/blob/master/ui/intermittent-failures/DropdownMenuItems.jsx) for generating the menu with check mark for active selection. But it uses reactstrap (react-friendly version of Bootstrap that uses the librarys' CSS but replaces the jquery). So putting some of this boilerplate into a library doesn't make sense unless it is already using reactstrap (or else you'd have to change it to standard html/jsx). Same with the delta bar charts - that was created with reactstrap components. So this new library might need to pick a UI library as a dependency to avoid reinventing the wheel with regards to interactivity.

Thanks for the examples - I see what you mean now. Basically the whole scaffolding for getting a dashboard up and running.

**Comment by aimenbatool** [comment]
@klahnakoski thanks for mentioning me. This is too much for me to understand I might take little longer to absorb things and give my input. :)

**Comment by klahnakoski** [comment]
> So this new library might need to pick a UI library as a dependency to avoid reinventing the wheel with regards to interactivity.

@sarah-clements, yes you got it. A big part of the project is deciding on the libraries, like reactstrap, that we should standardize on. We have many people, like yourself, that already know of tools; I want to package that knowledge so people, like me, can avoid making a thousand ill-informed decisions just to standup a dashboard.

**Comment by klahnakoski** [comment]
Here is an example of the `index.jsx` problem:

![image](https://user-images.githubusercontent.com/2334429/55182071-5fa87b00-5163-11e9-8c8b-e2771ff2a220.png)

**Comment by armenzg** [comment]
When I wrote that code I created too many files (It's a pattern I'm moving away from). A lot of the files could be folded into a single file or handful of files; keeping index.js for the one that contains the function that is needed by the UI.

**Comment by klahnakoski** [comment]
This has been reorganized a while ago now:  Components are grouped by how they use each other.
