### ISSUE TITLE
https://health.graphics/android/graph?site=https://www.tripadvisor.com is broken

### ISSUE THREAD

**Issue by overholt** [mozilla-frontend-infra/firefox-health-dashboard#289]
I first noticed this was broken some time on 2019-02-04 and it's still broken. I get:

"There has been a critical error. We have reported it. If the issue is not fixed within few hours please file an issue:"

**Comment by klahnakoski** [comment]
This is not broken for me, but I will keep it open as we merge some PRs today.

**Comment by klahnakoski** [comment]
https://health.graphics/android/graph?site=https://www.tripadvisor.com/

**Comment by klahnakoski** [comment]
Yes, looking at https://health.graphics/android I can see `www.tripadvisor.com/` (with trailing slash) is the site.

Notice `people.com/amp-stories/royal-a-to-z/`  and `people.com/amp-stories/royal-a-to-z`  have two different behaviours.

**Comment by klahnakoski** [comment]
this is fixed
