### ISSUE TITLE
Enable linting rules and refactor code accordingly 

### ISSUE THREAD

**Issue by aimenbatool** [mozilla-frontend-infra/firefox-health-dashboard#293]
In https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/281, custom linting rules are removed and `    '@mozilla-frontend-infra/react-lint'` has been added for linting rules. 

Some rules are disabled and need to be enabled and fixed accordingly. 

if you search `disable` in your editor you will find all files having disabled linting rules. Fix them one by one.

**Comment by aimenbatool** [comment]
@klahnakoski, @sarah-clements, @djmitche 

Linting rule: https://eslint.org/docs/rules/no-param-reassign
Result object [here ](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/utils/BackendClient/NimbledroidApiHandler.js#L19)is reassigned in several places. 
[for example](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/utils/BackendClient/NimbledroidApiHandler.js#L31). 

And this rule isn't allowing mutating the result object inside reduce while reducer need to udate the object. 
Read discussion: https://github.com/eslint/eslint/issues/8581 

Now we have two option 
- use the spread operator method in our reducer (if applicable) which isn't an efficient way
- disable this rule  

What are your suggestions?

**Comment by aimenbatool** [comment]
I am mentioning all the rules causing issues in separate comments to get input to solve it. 

Rule: https://eslint.org/docs/rules/no-restricted-syntax 

This rule is causing error [here](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/quantum/target-status.jsx#L10-L14). 
This rule disables some of the language features as says that `you might decide to disallow the use of try-catch or class, or you might decide to disallow the use of the in operator.`

So in our code it looks like the error is due to `of` operator. 
Look like there is no hard and fast rule about it and [we can disable](https://eslint.org/docs/rules/no-restricted-syntax#when-not-to-use-it) it or customise if we want to use language features. 

What is the most suitable way of fixing it?

**Comment by klahnakoski** [comment]
@aimenbatool 

If you can not fix the problem easily, then add es lint comment to disable the lint checks.

Adding the comment will change the code less, which will make merging easier:  Leave it to the person touching the code next to solve the problem.

**Comment by aimenbatool** [comment]
@klahnakoski 

Sure, Thanks.

**Comment by klahnakoski** [comment]
@aimenbatool is there anything left for this issue?  I think all that is left are individual lint fixes, which we can deal with as required.  If there is nothing else, please close this.

**Comment by aimenbatool** [comment]
@klahnakoski yes only individuals are left.
