### ISSUE TITLE
Can not see netlify logs

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#297]
For some reason netlify tests are not passing.  I can not see the logs

![image](https://user-images.githubusercontent.com/2334429/52489041-40439780-2b8f-11e9-9680-e656abd37b11.png)

All inks to netlify end up with "Page not found", "You might not have permissions to see this page."

**Comment by aimenbatool** [comment]
@klahnakoski this (https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/283 ) conversation might help you to pass this https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/295

**Comment by klahnakoski** [comment]
@helfi92 @aimenbatool @sarah-clements @djmitche 

Who is able to grant access so I may see the logs?

**Comment by klahnakoski** [comment]
@aimenbatool thank you, I tried changing the yarn version to match what works for me locally, but really I am just guessing why the failure happens because I cannot see logs.
