### ISSUE TITLE
Discussion: Tooltip values for initial data points

### ISSUE THREAD

**Issue by 2alin** [mozilla-frontend-infra/firefox-health-dashboard#306]
Hi everyone, I've just started tinkering with the repo in order to start contributing to it. 
I open this issue because I'm not sure if the first data points in the Perfherder graphs should display '**n/a**' in many of the tooltip fields [1].
 
I think at least `currentData` (second line from the bottom) should match the value of such point (261 at the example given). And for `delta` and `deltaPercentage`, I should suggest displaying '0' instead (there's no previous data point, so there's no increment). 
 
What do you think @aimenbatool? I think you are the one who has been working on this :sunglasses: . I have made some changes already in the code to handle this issue, but I am not sure if I should open a pull request or not. Please let me know what do you think.

[1]
![screenshot_20190216_022919](https://user-images.githubusercontent.com/4089035/52896972-455aa500-3194-11e9-84c5-3e4678432bc9.png)

**Comment by aimenbatool** [comment]
@2alin Hi, Thanks for pointing out. Adding `currentData` value makes more sense to me, looks like a miss. Adding `0` also sounds good but let's take @sarah-clements 's input on it.

**Comment by sarah-clements** [comment]
@2alin Where do you see the tooltip as shown in your initial comment? When I navigate to https://health.graphics/android, I don't see the delta percentage:
![screen shot 2019-02-18 at 9 54 52 am](https://user-images.githubusercontent.com/19615783/52968855-66252500-3363-11e9-9243-2c52095f10d8.png)

**Comment by 2alin** [comment]
@sarah-clements I used this url https://firefox-health-dashboard.netlify.com/android which is in the repo frontpage. And also, can be noticed in the current status of the repo at [perfherderFormatter.js](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/utils/perfherder/chartJs/perfherderFormatter.js#L41) (line 41).

**Comment by sarah-clements** [comment]
Ok @2alin, thanks for opening the discussion to point that this detail. Please feel free to open a pull request.

**Comment by aimenbatool** [comment]
@sarah-clements  this looks strange. 

I also can see the percentage change and higher or lower information on https://health.graphics/android.

I just notice after your comment. We pushed this in our latest PR and that code seems to be same but not giving the expected result. 
It's working well on my local machine. 

I will dig into it to figure out the issue.

**Comment by sarah-clements** [comment]
@aimenbatool and @2alin There might a problem with the syncing between netlify and the live production site (https://health.graphics). @klahnakoski might be able to help.

**Comment by 2alin** [comment]
Same as Sarah, I'm getting outdated tooltips  from https://health.graphics/android in the Perferherder compared with https://firefox-health-dashboard.netlify.com/android

**Comment by sarah-clements** [comment]
I checked now and [health.graphics](health.graphics/android) seems to be up-to-date (since I'm not a maintainer I don't have insight into the deployment when code is merged so I'm not sure what resolved it).

**Comment by klahnakoski** [comment]
@2alin Sorry for the late reply, I was away for the weekend.  As per my PR, please do not show zero.  Rather, remove the whole `Δ n/a` line from the tooltip.
