### ISSUE TITLE
Clean up perf-goggles

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#311]
The code for getting data series is a bit complicated.  Here is the simplified call tree

* `queryPerformanceData` - exported endpoint
  * `parentSignatureInfo` - Finds the signatures for the data series for the given 
    * `signaturesForPlatformSuite` - Get short list of signatures from TH
      * `queryPlatformSignatures` -  called multiple times, for the same config 
    * `treeherderOptions` - necessary to decode the other TH calls
      * `queryAllTreeherderOptions` - actual call to TH
      * `transformOptionCollectionHash` - some minor transformation
    * `findParentSignatureInfo` - finds the matching signatures
  * `fetchPerfData` - get actual series, and merge results
    * `tranformData` - some minor transform
  * `querySubtests` - does a `parent_signature` call to get subtests
  * `fetchSubtestsData` - get the subtest data
    * `fetchPerfData` - actual call to TH

This should be changed to leverage Treeherder's filtering options; specifically on tests.

* `queryPerformanceData` - will accept {var: value} pairs to send to TH
  * `getAllOptions` - a Promise to return all the TH options
  * `getSignatures` - a cached table of values from TH, one call with `{framework: 10}` can pull everything in a single call
  * `fetchPerfData` - a Promise to get data for a signature

The intention is `queryPerformanceData({test: "loadtime", suite:"tp6m"})` will provide us with just the load times across many suites.

**Comment by 2alin** [comment]
Beautiful!! 
and I'm indebted to you for this summary which I'll refer from now on, because the one I made while trying to understand the repo's code tree (and which I'm still referring) is not the most clean of all :rofl: 
![layout](https://user-images.githubusercontent.com/4089035/53074214-c3c68800-34af-11e9-8e56-4a1572544be2.jpeg)

**Comment by klahnakoski** [comment]
this code is gone
