### ISSUE TITLE
browser back and forward do not update page

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#314]
Prthessing the forward and back buttons on the browser updates he URL, but does not update the page. 

`withNavigation()` should handle this problem

**Comment by exturingmachina** [comment]
Hello, would it be okay if I worked on this?

**Comment by djmitche** [comment]
Go ahead @exturingmachina !

**Comment by shashankgaurav17** [comment]
Hey, Can I work on this ?

**Comment by klahnakoski** [comment]
@shashankgaurav17   yes please!

**Comment by TrangEmily** [comment]
Hi @klahnakoski I can't reproduce this issue. When I pressed backward and forward button on Firefox it reload the page. Is it solved already? Thank you.

**Comment by klahnakoski** [comment]
go to the tp6mobile page:

https://health.graphics/android/tp6m?test=loadtime&platform=android-hw-g5-7-0-arm7-api-16

update the platform to P2, notice reload

press back button on browser, notice the URL changes, but data does not

**Comment by TrangEmily** [comment]
Yes when I go to that pape, forward and backward changes the URL but not reload the page. However, I can not see the data. Is it another issue or I lack something on my installation?
This is on Android page (other parts show normal graph and data)
<img width="1663" alt="Screen Shot 2019-03-29 at 11 20 03 AM" src="https://user-images.githubusercontent.com/42683686/55254430-0dc02d80-5215-11e9-9f9b-097fbf193171.png">
And this is when I click "more" link which go to the link you gave in above comment:
<img width="1663" alt="Screen Shot 2019-03-29 at 11 20 29 AM" src="https://user-images.githubusercontent.com/42683686/55254471-26c8de80-5215-11e9-91f1-1860955fe9bf.png">

**Comment by klahnakoski** [comment]
It looks like you have not network connection.  What does the network tab in the browser say?

**Comment by TrangEmily** [comment]
No I run on local host, other parts show normally as below
<img width="1654" alt="Screen Shot 2019-03-29 at 12 58 56 PM" src="https://user-images.githubusercontent.com/42683686/55259315-8ed1f180-5222-11e9-8fa8-b611bc8bd3b7.png">

**Comment by klahnakoski** [comment]
@TrangEmily  And what does the debugger say?

![image](https://user-images.githubusercontent.com/2334429/55259610-8a1a3700-523c-11e9-8abf-c1176636ee32.png)

**Comment by TrangEmily** [comment]
And this is the network tab
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/42683686/55259745-c5f4d280-5223-11e9-8632-55f2775a30a3.png">

**Comment by klahnakoski** [comment]
@TrangEmily how about the last few requests at the bottom?  ping me on irc as ekyle so we can get this resolved faster
