### ISSUE TITLE
Update Tab Switch (tps) based on the test being renamed to tabswitch

### ISSUE THREAD

**Issue by davehunt** [mozilla-frontend-infra/firefox-health-dashboard#322]
Once [bug 1451860](https://bugzilla.mozilla.org/show_bug.cgi?id=1451860) lands we will need to update the name for the 'Tab Switch (tps)' graph, and to start pulling in data from the new test name. We do not currently intend to rename the existing test results, so we should plot both the 'tps' and 'tabswitch' results as a single line.

![screenshot_2019-02-28 firefox health dashboard](https://user-images.githubusercontent.com/122800/53552655-b8b8cb00-3b33-11e9-9d57-ae772ff4fc5b.png)

**Comment by davehunt** [comment]
I notice this graph is now reporting an error. Could you take a look at this @klahnakoski?

**Comment by klahnakoski** [comment]
The new name is now in effect, I will fix this chart

**Comment by klahnakoski** [comment]
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/331

**Comment by davehunt** [comment]
Fixed in 5fc78e1fe0e78b938d2492e1d57a6b8c8dd0e12c. @klahnakoski it looks like the graph shows ~4 weeks of data. Once we only have tabswitch results would it make sense to follow-up and remove the tps source?

**Comment by klahnakoski** [comment]
yes, I will remove tps later.
