### ISSUE TITLE
improve README.md with better setup instructions

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#323]
The setup instructions can be improved somewhat. Include setups for installing node and yarn, a suggestion for the IDE, and what plugins should be used. 

The best person to do this is a person that has not setup this project before.

**Comment by aimenbatool** [comment]
I would like to take this issue. Updating README is in my list since long I also have a few content to update. 

If anyone else is interested, we can work together :) I will start working on it after a week or two.

**Comment by vansjyo** [comment]
@klahnakoski  I would like to work on this issue?

**Comment by klahnakoski** [comment]
@vansjyo  yes, please!  Especially if you have not setup this project before.

@aimenbatool or I can answer your questions and provide reviews.

**Comment by a-deeb** [comment]
Hi, I would like to help out on the Readme file

**Comment by vansjyo** [comment]
@klahnakoski . I have not set up this project before.

**Comment by aimenbatool** [comment]
@vansjyo Go ahead and open a PR. 
We can not assign the issue to someone who isn't a project participant/collaborator. 

Consider this issue is assigned to you. We will share our feedback on your PR. 
Thanks!

**Comment by vansjyo** [comment]
@aimenbatool. Ok. Thank you. I did not know about it.

**Comment by aimenbatool** [comment]
@vansjyo I just noticed that @a-deeb has already opened a PR https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/325 for this issue. I think you should wait for a-deeb to complete. :) 
You can pick any other issue meanwhile.

**Comment by vansjyo** [comment]
@aimenbatool  Ok.
