### ISSUE TITLE
Rename "Chrome" to "Chromium" in Raptor-run test charts

### ISSUE THREAD

**Issue by stephendonner** [mozilla-frontend-infra/firefox-health-dashboard#326]
What we call "Chrome" on at least https://health.graphics/quantum/32 and https://health.graphics/quantum/64 is, actually, the open-source version: Chromium[0][1].

To help clear up confusion about, set clarity on, and match expectations across the board, we should rename and/or denote that.

[0 ]https://wiki.mozilla.org/Performance_sheriffing/Raptor#Raptor
[1] https://www.chromium.org/Home

@klahnakoski o hai!  I might be able to help with a (simple?) string-renaming patch, here, but TBH, I'm not sure if it touches other modules, and/or if there are places where it'll break anything schema-related (but hopefully Rob and others will know).

/cc @rwood-moz @davehunt @stuartphilp

**Comment by klahnakoski** [comment]
@stephendonner please close this if it looks good now.

**Comment by stephendonner** [comment]
Thanks, @klahnakoski!  This looks good to me; others here can comment/reopen if I've missed something.

![post-fix-health-graphics](https://user-images.githubusercontent.com/387249/53776491-0d00d980-3eab-11e9-9b52-08c80b8e324a.png)
