### ISSUE TITLE
Improve Coverage

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#333]
We can improve coverage by writing tests! Once you have setup this project, you should be able to run `yarn test` to run all the tests.  Then start looking for something that is not covered.  

Go to Coveralls to take a look:

![image](https://user-images.githubusercontent.com/2334429/53816962-90b1d900-3f32-11e9-8e64-4f7393cc0914.png)

There is a section that lists all the files, with their coverage.  You can list all files and then sort them by coverage percent, or by number of line missing coverage.  These will give you a short list of the "biggest wins"

![image](https://user-images.githubusercontent.com/2334429/53817014-a3c4a900-3f32-11e9-8e57-d23f1115978b.png)

Pick a file, look in the `tests\` directory for a similar test, copy it, and make a new test.  Feel free to make a PR with an incomplete test if you have questions: 

Use  `git commit --no-verify ...` and `git push --no-verify ...` to push incomplete code to your PR.

**Comment by leslie-alldridge** [comment]
I've added some tests and can continue to do more once I'm back home from work. PR will be up soon @klahnakoski

**Comment by BrunoDM2943** [comment]
@klahnakoski, I have added some tests. I want to do some more later...Question: it makes senses the folder src/vendor be in coverage report?

#419

**Comment by klahnakoski** [comment]
`src/vendor` will be in the coverage report, even if we test none if it's functions.  

The plan is to have the `vendor` directory separate itself from this project, and become a package with it's own tests suite.  Since `vendor` is still new, and this project is the only one using it, we keep the tests (and coverage) here for now.

**Comment by BrunoDM2943** [comment]
Ok, gotcha

**Comment by tybanash** [comment]
interested in contributing to this. Please canyou giv eme clues on how to set up this project

**Comment by tybanash** [comment]
i am interested in contributing to this. Please can you give me clues on how to set up this project?

**Comment by RajendrasinhParmar** [comment]
Hello, I'm working on unit testing of some files where there are API requests on-page. And for that, I'm trying to use the mock file that is created with sample data inside it. Can someone verify that is it the file that we can use for mocking API response?

**Comment by klahnakoski** [comment]
@RajendrasinhParmar  You may consider recording the current API response to generate the files you are looking for.  This will be a big help, since most of the coverage is realized after the API calls. 

Feel free to open a PR, even if your work is incomplete (`git push --no-verify`), so I can answer your questions more specifically.

**Comment by RajendrasinhParmar** [comment]
@klahnakoski Thank you for the prompt response. I'll look into ways to achieve this. by recording the API response. However, I think As the components that are using the response of API to render the actual data do not process the data them selfs. So we can probably divide our testing into two parts.

1.  Snapshot testing that will actually test the snapshots of the component according to data. In this, we can actually mock the API response by already created API response file.
2. The second will be other non-UI components' unit testing where we can cover other parts of the application which are just functions to process and parse the data.

As you said some API will not change often we can statically record them as ultimately the rendering logic or the parsing logic will definitely change based on the API if the API response changes. So If our UI components are independent of the API change(Which I need to check by going through code), We can separate the testing as the above approach.

I'll try to look into it in more details and will see what can I do to properly handle the unit testing.

**_Can you explain Point No. 1  in a bit more details?_**

**Comment by klahnakoski** [comment]
Right now the snapshot testing is done with broken API calls; so the templates contain a minimal skeleton of what actually shows in a live site.  Mocking the API calls will give a richer response, and test more visual aspects.  For example, some icons only show when there is data; mocking API calls will allow us to confirm those icons are showing. In general, we will be able to test the END PRODUCT, not just some 1/2 rendered version.  Mocking the API calls will also allow us to test the code in `componentDidMount()` which ultimately calls much of the non-ui code to do the processing necessary to show the components and improves our code coverage numbers.  We get two wins for one:  More detailed template comparison plus higher code coverage.

We could add unit testing to the non-ui code.  That is already done for the lower level libraries (in the `vendor` directory), but I do not think it would be useful for non-ui code in general: Much of the code is dedicated to arranging data for a particular business need, and those needs change quickly over time.  These quickly changing needs are the nature of the business: Projects run for months, and then the charts are no longer required.  The code is good enough to deliver the end product, and soon it will expire.

But, we ARE testing the non-ui code if we mock the API calls:  These are not explicit unittests, but the coverage shows were are running the code, and whatever that code does, it produces the correct visual output.  With coverage, we will be able to see what non-ui code is not run, and ensure there is a visual template to cover that non-ui code.  Therefore, we can be confident all our code is useful, and it is run, and it produces the correct end product.

In general, only test what you really need to test, and use coverage to ensure you are testing all the code paths.  You can avoid unit testing the internal workings of your code if some higher-level test can provide coverage.  Avoiding a unittest means less test code to write, and less work to refactor when you need to.  Unit testing is good for testing stable APIs, or APIs that are shared with other humans.  But the most of the non-ui code in this project is very particular to the short lived business project it is supporting.   

On the subject of my first point: During jest testing, we get `fetch is not defined`, thrown from `fetchJson()`.  I do not know the Node equivalent of `window.fetch` in the browser.  If `fetchJson()` is fixed to work in both the browser and Node, then we win big!  The existing template tests can be updated to be richer, and compare more components: We can run `yarn test -u` and update the templates and automatically get a more robust set of tests!  Well, the data keeps changing, so the tests will not pass a few seconds later, but you will see the coverage improve immensely as all the code that processes the data from the API calls gets called into action.  In any case, getting `fetchJson()` to work on Node is valuable enough to warrant it's own pull request.

**Comment by RajendrasinhParmar** [comment]
@klahnakoski Thank you for the explanation. I'll keep this in mind and will work on this approach now.

**Comment by klahnakoski** [comment]
Maybe you can use https://www.npmjs.com/package/node-fetch

**Comment by RajendrasinhParmar** [comment]
I'm planning to use https://www.npmjs.com/package/jest-fetch-mock that probably will be specific to testing environment but will look into your suggestion as well

**Comment by klahnakoski** [comment]
@RajendrasinhParmar good!  it looks like `jest-fetch-mock` uses [cross-fetch](https://www.npmjs.com/package/cross-fetch), which is similar to `node-fetch`.

**Comment by klahnakoski** [comment]
... if what you have works for you, then no need to distract yourself with my suggestion.

**Comment by klahnakoski** [comment]
I am opening this bug up for others

**Comment by RajendrasinhParmar** [comment]
Yeah sure. Sorry as i got stuck in some other work lately. 😟 Still I'll create and MR once I'll update code coverage for any files. Just to update that I'd successfully setup mocking for fetch request. Which is now working as expected and it's not going ans requesting actual URL in jest execution.

**Comment by klahnakoski** [comment]
@RajendrasinhParmar 

Feel free to make a PR and commit/push with `--no-verify` so that I can give you feedback on what you have so far.  No need to get the whole thing working in a single push.

**Comment by wicked-kiD** [comment]
Hi guys! Can I join you to increase coverage? I've never contributed to opensource, want to try some.

**Comment by klahnakoski** [comment]
@wicked-kiD   Yes! Thank you for volunteering!

The first step is to find some code you think should be covered.  

https://coveralls.io/github/mozilla-frontend-infra/firefox-health-dashboard?branch=master

Unfortunately, it seems coveralls has a problem right now with sorting  

https://github.com/lemurheavy/coveralls-public/issues/1365   

So you may want to consider changing the `travis.yml` file to submit coverage to codecov.io instead of fixing coverage.   

Decide what you would like to fix.  Fork this repo, clone it to your local machine, make a branch, push, and make a PR.  (use `--no-verify` during commit and push to avoid checks)   

We will use your PR to discuss specifics.

**Comment by klahnakoski** [comment]
@wicked-kiD 

Looking at this issue, it seems to have expanded to include a number of problems.  It should be split up.

**Comment by klahnakoski** [comment]
@js636f   Please look at https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/665  first.

**Comment by js636f** [comment]
@klahnakoski OK, thank you

**Comment by kimberlythegeek** [comment]
As @klahnakoski mentioned, this issue has become a bit bloated and needs to be broken down into smaller, separate issues. I will lock this conversation and open new issues regarding code coverage
