### ISSUE TITLE
Move generic code to vendor directory

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#334]
The `src/vendor` directory is a repo of code from other projects. This Health dashboard has some useful code that can contribute to that repo, and so be moved to `src/vendor` for export.

**Comment by klahnakoski** [comment]
This is a good first issue because, in theory, it is a simple rename.  Looking through the code, and discussing what is generic is a good learning experience.

**Comment by Paarmita** [comment]
Hey, @klahnakoski I would like to work on this issue.
Do I need to rename the files`src/vendor ` from other projects when copying in `Health dashboard`?

**Comment by klahnakoski** [comment]
@Paarmita this project is firefox-health-dashboard, and we intend to break it into two projects.  One part is the code we can reuse, which we put in the `src/vendor` directory, and the other part is everything else.  Before this project is split, we should move some more things into the `src/vendor` directory.  

Look through the code of this project:  What parts have no relation to firefox-health-dashboard, yet can conceivably be used by another dashboard? What parts keep data extraction separate from data presentation?
