### ISSUE TITLE
BugzillaUrlContainer's parameters are OR'd but should be AND'd like BugzillaGraph's parameters

### ISSUE THREAD

**Issue by cpeterso** [mozilla-frontend-infra/firefox-health-dashboard#346]
The BugzillaUrlContainer queries don't work as I would expect them to. BugzillaGraph's `parameters` properties are AND'ed together but BugzillaUrlContainer's `parameters` properties seem to be OR'd together.

For example, the "Open fenix:p1 bugs" link on https://health.graphics/android currently has a `parameters: {product: 'GeckoView', resolution: '---', whiteboard: '[geckoview:fenix:p1]', }` and links to a Bugzilla query that returns 356 bugs because it includes bugs in the "GeckoView" product that don't have whiteboard string "[geckoview:fenix:p1]".

https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/views/Android/index.jsx#L31-L38

https://bugzilla.mozilla.org/buglist.cgi?columnlist=priority%2Ccomponent%2Cassigned_to%2Cbug_status%2Cshort_desc%2Cstatus_whiteboard%2Cchangeddate&order=Bug%20Number&product=GeckoView&resolution=---&whiteboard=%5Bgeckoview%3Afenix%3Ap1%5D&list_id=14607641

Whereas the "GeckoView Fenix bugs" graph has `parameters: {product: 'GeckoView', resolution: ['---', 'FIXED'], whiteboard: '[geckoview:fenix:p1]',}` and currently returns 0 open bugs, which is correct.

https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/views/Android/index.jsx#L31-L38

**Comment by armenzg** [comment]
Thank you for filing it!

**Comment by klahnakoski** [comment]
use https://github.com/klahnakoski/MoDevMetrics/blob/dev/html/modevlib/Bugzilla.js for converting from json expressions to bugzilla rest queries

**Comment by klahnakoski** [comment]
Proposed fix  https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/462

**Comment by klahnakoski** [comment]
@cpeterso  May you look at this PR?  If I am updating the queries, I might as well update the chart contents too.
