### ISSUE TITLE
Nimbledroid data is old

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#349]
Nimbledroid stopped arriving Feb28

**Comment by klahnakoski** [comment]
@armenzg I do not have time to look into this problem.  I hope you can fix it.

**Comment by klahnakoski** [comment]
I do not think it is this dashboard, rather the endpoint gathering the data:

        result = http.get_json("https://firefox-health-backend.herokuapp.com/api/android/nimbledroid?product=org.mozilla.geckoview_example&version=3")
        max = MAX(Date(v).unix for v in result.scenarios['Cold Startup'].date)
        Log.note("{{time}}", time=Date(max))

returns

    2019-03-01 03:09:53.605000

**Comment by armenzg** [comment]
I'm investigating this on the backend repo.

**Comment by armenzg** [comment]
I've spoken with @npark-mozilla and he has not been uploading any new apks since the end of February.

**Comment by npark-mozilla** [comment]
We're shutting down Focus uploads, and working on auto uploading of reference browser on CI
