### ISSUE TITLE
Show targets (Fennec 64/65)

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#354]
as per  https://docs.google.com/spreadsheets/d/1xuYdCodmiFY-NmAXq_8WTcO_WMfsZVNNeiGCr-w2xAY/edit#gid=0

**Comment by davehunt** [comment]
Please use the tab named "Fennec64 vs FenixGV67 tp6m-warm-pageload" for latest Fennec v64 warm load values.
