### ISSUE TITLE
Add more nimbledroid platfoms

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#364]
"fenix" and "reference browser" data is available on nimbledroid.  The config file must be updated with the correct "products".  I think.

https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/utils/nimbledroid/config.js

**Comment by klahnakoski** [comment]
@armenzg I will need to connect words like "fenix" to the required backend product that represents the same.  I imagine a list of products (and version numbers) will suffice.

**Comment by klahnakoski** [comment]
@armenzg I think the version number has nothing to do with the product; it seems to not be used by the `queryNimbledroidData()`

https://github.com/mozilla/firefox-health-backend/blob/master/src/android/routes.js#L33
https://github.com/mozilla/firefox-health-backend/blob/master/src/utils/apis/queryNimbledroidData.js#L48

**Comment by armenzg** [comment]
The version was for the version of the endpoint, however, I dropped that functionality:
https://github.com/mozilla/firefox-health-backend/commit/58b39fdf5182eff35f08e9a0f50fbb1b54f268f5#diff-926e65bb5de596d532621fa5344febc5

That was missed. I pushed a change for it.

**Comment by armenzg** [comment]
This seems to be working:
https://firefox-health-backend.herokuapp.com/api/android/nimbledroid?product=org.mozilla.reference.browser.debug
