### ISSUE TITLE
Tooltip click-lock prevents tooltip from showing

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#376]
As per https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/373#issuecomment-478579060

* Click on a datapoint to lock the tooltip
* Move mouse, notice points no longer have a tooltip (that would be 2 tooltips on a single chart)
* Click on a point (exactly) Notice the tooltip is unlocked **but not changed**
* Move mouse to have tooltip show current point

1 .clicking on a datapoint should advance the tooltip to that point
2. it would be nice if locked tooltips allowed other tooltips to show

**Comment by klahnakoski** [comment]
still a problem with https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/441

**Comment by klahnakoski** [comment]
@arnold-iakab this issue drives me crazy!  But, it is not important.

**Comment by noi5e** [comment]
@klahnakoski it's me again, an Outreachy applicant. maybe this is something i can work on as a new contributor?

**Comment by kimberlythegeek** [comment]
Hi @noi5e ,  thank you for your interest! I am the other mentor on this project, feel free to reach out with any questions you may have

**Comment by noi5e** [comment]
@kimberlythegeek thanks, appreciate your patience with the sudden influx of new contributors. i'll take a look today.

**Comment by kimberlythegeek** [comment]
@noi5e of course!
