### ISSUE TITLE
Chrome data has been renamed to Chromium

### ISSUE THREAD

**Issue by davehunt** [mozilla-frontend-infra/firefox-health-dashboard#408]
Our Chromium test data now accurately reflects the target browser variant in the name. This means all graphs that plot "chrome" data will need to be updated to pull in data from the new "chromium" tests. For example: https://treeherder.mozilla.org/perf.html#/graphs?timerange=5184000&series=mozilla-central,1870841,1,10&series=mozilla-central,1934605,1,10&series=mozilla-central,1982114,1,10

Also note the Speedometer results appear to be missing the platform name change to "shippable". Example: https://treeherder.mozilla.org/perf.html#/graphs?timerange=5184000&series=mozilla-central,1791369,1,10&series=mozilla-central,1981461,1,10&series=mozilla-central,1933151,1,10

**Comment by klahnakoski** [comment]
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/409

**Comment by klahnakoski** [comment]
@davehunt  close this if it is done

**Comment by davehunt** [comment]
Looks great, thanks @klahnakoski!
