### ISSUE TITLE
Show all sites for GVE cold page load

### ISSUE THREAD

**Issue by davehunt** [mozilla-frontend-infra/firefox-health-dashboard#424]
We're now running cold page load for all tests against GeckoView Example. Here's an example showing the aframe.io test: https://treeherder.mozilla.org/perf.html#/graphs?series=mozilla-central,2007109,1,10&series=mozilla-central,2007219,1,10&series=mozilla-central,2007249,1,10

**Comment by klahnakoski** [comment]
Done: https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/426  
preview: https://deploy-preview-426--firefox-health-dashboard.netlify.com/android/tp6m?test=cold-loadtime&platform=geckoview-p2-aarch64
