### ISSUE TITLE
Speedometer and Unity WebGL are labeled "Duration", not higher-is-better score

### ISSUE THREAD

**Issue by cpeterso** [mozilla-frontend-infra/firefox-health-dashboard#429]
The Speedometer and Unity WebGL graphs on https://health.graphics/android are both labeled "Duration", where a lower value is better performance. However, Speedometer is a higher-is-better score. I suspect Unity WebGL is also higher-is-better because both Speedometer and Unity WebGL appeared to "regress" (their value increased) after ARM64 PGO landed on May 8. I think these two graphs should be inverted so lower appears faster.

**Comment by klahnakoski** [comment]
Fixed in a larger PR https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/431/commits/6c6805d9e275dd4c12be1b331c4539c975ead959
