### ISSUE TITLE
Show media streaming playback statistics

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#430]
Example

https://treeherder.mozilla.org/perf.html#/graphs?timerange=604800&series=mozilla-central,2043558,1,10

**Comment by whimboo** [comment]
Please note that the overall score shows the mean of dropped frames. As described in the OKR we only want to have the percentage of dropped frames for the 1080p30@1.0x.

**Comment by klahnakoski** [comment]
@whimboo May you tell me a bit more about

* H264 vs VP9 - do they have humane names?  are they just-different-video-encodings?
* Plain "H264" vs "PlaybackPerf.H264" - How are they testing different things? Is one a baseline?

Thank you

**Comment by klahnakoski** [comment]
@whimboo   It looks like most tests have zero dropped frames, with the rest dropping one. This averages to  0.0% dropped frames.  Do you have some suggestion on how to make this useful?  

This preview is showing dropped frames (not percentage) because the % is too small.  This is one combination that shows at least one dropped frame:

https://deploy-preview-432--firefox-health-dashboard.netlify.com/playback?platform=win-aarch64&browser=firefox&suite=Plain&encoding=VP9

**Comment by klahnakoski** [comment]
Work proceeding here:

https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/432

**Comment by klahnakoski** [comment]
@whimboo  ok, it looks like mac has interesting data: 

http://localhost:5000/playback?platform=mac&browser=firefox&suite=Plain&encoding=VP9

**Comment by whimboo** [comment]
>     * H264 vs VP9 - do they have humane names?  are they just-different-video-encodings?

You should keep those names, yes. Everyone involved in media knows about those video codec names. And yes, they are completely different codecs.

For details see:
https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC
https://en.wikipedia.org/wiki/VP9

>     * Plain "H264" vs "PlaybackPerf.H264" - How are they testing different things? Is one a baseline?

Please don't care about `PlaybackPerf.H264`. This was just the formerly reported name. Given that the prefix is always `PlaybackPerf.` we decided to completely get rid of it. As such only watch out for `H264.[..]`.

**Comment by whimboo** [comment]
> @whimboo It looks like most tests have zero dropped frames, with the rest dropping one. This averages to 0.0% dropped frames. Do you have some suggestion on how to make this useful?

Having 0.0% of dropped frames is our ultimate goal. But as you noticed in a follow-up comment this doesn't happen across all devices and platforms yet. Especially not for MacOS and aarch64 on desktop, and the mobile platforms. 

> This preview is showing dropped frames (not percentage) because the % is too small. This is one combination that shows at least one dropped frame:
> 
> https://deploy-preview-432--firefox-health-dashboard.netlify.com/playback?platform=win-aarch64&browser=firefox&suite=Plain&encoding=VP9

I would leave this question up for Eric Smyth from product but for the moment they may want to have the percentage. Reason is - as I mentioned in my first comment - that the current OKR has a 4% limit. Also we might not need graphs for all the videos but only for those as covered by the OKRs. @davehunt, can you follow-up with Eric on that?

**Comment by klahnakoski** [comment]
@whimboo 

> I would leave this question up for Eric Smyth from product but for the moment they may want to have the percentage. 

Oh yes, I agree!!  I only used total dropped frames on this experimental page so we can actually see something, other than zeros, on the charts.

Thank you for the answers!

**Comment by klahnakoski** [comment]
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/458
