### ISSUE TITLE
Remove 404 and 202 sites from TP6

### ISSUE THREAD

**Issue by davehunt** [mozilla-frontend-infra/firefox-health-dashboard#438]
I notice that we have graphs for:

* Wikipedia 404-202
* Wikipedia 404-404
* eBay 404-202
* eBay 404-404

These were temporary whilst we observed the impact of upgrading from mitmproxy 2.0.2 to 4.0.4 and they can now be removed.

**Comment by klahnakoski** [comment]
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/441/commits/032edd0938a3709ae17ab663e9d348e823e524d0

**Comment by davehunt** [comment]
@klahnakoski does this require a new deployment? I still see these visualisations.

**Comment by klahnakoski** [comment]
@davehunt yes, this is waiting for deploy
