### ISSUE TITLE
Add Netflix to TP6 (desktop)

### ISSUE THREAD

**Issue by davehunt** [mozilla-frontend-infra/firefox-health-dashboard#439]
With [bug 1511341](https://bugzilla.mozilla.org/show_bug.cgi?id=1511341) we landed a new test for Netflix, and we should soon start seeing results in Perfherder. Let's add this site to the TP6 graphs.

**Comment by davehunt** [comment]
Here's some data: https://treeherder.mozilla.org/perf.html#/graphs?series=mozilla-central,2072670,1,10&series=mozilla-central,2072665,1,10

**Comment by klahnakoski** [comment]
We will keep this open until we are also showing Linux perf results

**Comment by klahnakoski** [comment]
linux has been given its own issue
