### ISSUE TITLE
Add Twitter (Firefox) to TP6 (desktop)

### ISSUE THREAD

**Issue by davehunt** [mozilla-frontend-infra/firefox-health-dashboard#440]
It appears that the Twitter visualisation is missing Firefox data. Here's a link to the data in Perfherder: https://treeherder.mozilla.org/perf.html#/graphs?series=mozilla-central,1982073,1,10&series=mozilla-central,1936388,1,10&series=mozilla-central,1969856,1,10

![Screenshot 2019-06-26 at 11 36 02](https://user-images.githubusercontent.com/122800/60173475-b4ad6900-9806-11e9-9395-ea9ccf5f5685.png)

https://health.graphics/quantum/tp6?test=warm-loadtime&bits=64&past=2week&ending=2019-06-26

**Comment by klahnakoski** [comment]
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/454

**Comment by davehunt** [comment]
@klahnakoski I still don't see Firefox data on the Twitter visualisation. Does this require a new deployment?
