### ISSUE TITLE
Show times in UTC

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#443]
Especially for the Geomean charts, but everywhere else too.

**Note to Contributor**

This bug will require a good look into the ChartJS API:  You may be able to fool the API to think the browser is in the GMT timezone.  Or, maybe can provide your own format function: Converting xaxis time values into GMT strings. The `GMTDate.niceFormat` function should be a big help (since that whole library works with GMT exclusively)

**Comment by klahnakoski** [comment]
@arnold-iakab I think the ChartJS is still using local time on the axis, if you can fix this then everyone in the world will get to see the same chart. This is optional, remove yourself from the assignee if you find this uninteresting.

**Comment by lelouchB** [comment]
@klahnakoski Hello,  I am interested in this issue and want to work on this

**Comment by klahnakoski** [comment]
Yes please!

**Comment by lelouchB** [comment]
@klahnakoski  Just to be sure, to fix this issue we have to show time in UTC in different charts rather than GMT, although there is no time difference but for standard thing??

**Comment by lelouchB** [comment]
@klahnakoski can you please elaborate the issue?

**Comment by klahnakoski** [comment]
@lelouchB   Eventually, all chart requests end up here:

https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/90d92e7f9d21134df3b9e5fd63801e1819f646fd/src/vendor/components/chartJs/ChartJsWrapper.jsx#L214

This is the call to [ChartJS](https://www.chartjs.org/docs/latest/), which is the main charting library for this project (and the only one we plan to keep).  The charts are shown using the browser's timezone.  When I look at a chart, the chart shows the x-axis marked in Eastern Standard Time, while my coworker sees looks at the same chart in British Standard Time:  We see two different charts!  If I say "look at the data around 9am", he must translate that to "look at the data around 5am".

The mission is to search the ChartJS docs (or maybe the code, or maybe the forums) to find out how we can get ChartJS to show the time using GMT, so everyone sees the same chart.

**Comment by klahnakoski** [comment]
@lelouchB The very first step is to confirm you can stop the program with the browser debugger at the line I pointed to above. From there you can inspect the variables at that point, and you can explore the data structure that is sent to ChartJS.  You should be able to see the reference to the x axis, and the range of values it has.

Second, pick a chart that looks interesting enough:   Be sure it is one of the performance charts. Here is an Android chart:

![image](https://user-images.githubusercontent.com/2334429/72942120-ac87be80-3d40-11ea-836b-5b4c32541077.png)

Here it is in the code:  

https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/90d92e7f9d21134df3b9e5fd63801e1819f646fd/src/android/index.jsx#L227

Cutout everything except that chart so you have a working "page" that you can use for debugging.  The chart should still show when you load the page locally, and you should be able to stop the code in the ChartJsWrapper to see the x axis.  

Then you are ready to make the change need to show the time in GMT

**Comment by lelouchB** [comment]
@klahnakoski  Thanks a lot for explaining

**Comment by ellieya** [comment]
@klahnakoski @lelouchB Hi, I'm an outreachy intern applicant. Wanted to ask about the status of this issue. If it still has not been resolved, can I ask to take over this task?

**Comment by klahnakoski** [comment]
@ellieya This has still not been resolved.  It is now yours to attempt.

**Comment by kimberlythegeek** [comment]
Hi @ellieya! I am one of the mentors for the intern project. Feel free to ping me with any questions you may have, as well as request code reviews from me

**Comment by Kirti2502** [comment]
Hi! Can I take up the issue if it has not been resolved yet?

**Comment by ellieya** [comment]
@Kirti2502 Hi Kirti, I am currently working on the issue.

**Comment by ellieya** [comment]
Hi, I am really sorry about the lack of communication as of late!
I have been overwhelmed at my school/work due to the outbreak.
I should be able to resume progress on the issue starting this week.
I will let you all know if I am stuck on anything.
