### ISSUE TITLE
Fennec v64 results (for target numbers)

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#450]
https://treeherder.mozilla.org/perf.html#/graphs?series=mozilla-central,2069024,1,10&series=mozilla-central,2069060,1,10&series=mozilla-central,2068884,1,10&series=mozilla-central,2069056,1,10 
Currently ‘fennec’ for mozilla-central, which is ambiguous and could be confused with a build based on the commit from m-c, so we’re looking at making this more clear using ‘fennec64’ but we could use what we have for now.

**Comment by davehunt** [comment]
This should now be https://treeherder.mozilla.org/perf.html#/graphs?series=mozilla-central,2077955,1,10
