### ISSUE TITLE
Tooltip squeezes in Firefox, not Chrome

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#455]
If the point is to the right, then the tooltip will have a smaller width, nut in Firefox only.  

![image](https://user-images.githubusercontent.com/2334429/60521280-fa5dac00-9cb4-11e9-94a6-869d0cc3d517.png)

**Comment by annlinros** [comment]
Hi @klahnakoski 
Hi, I'm an outreachy intern applicant for May 2020. Can I work on this issue?

**Comment by annlinros** [comment]
Hi @klahnakoski 
I made a PR #664  for this issue.
Please review.

**Comment by klahnakoski** [comment]
@annlinros  Yes please!

**Comment by kimberlythegeek** [comment]
@annlinros Thank you for your contribution! I am the other mentor for this project, feel free to ask me questions as well.
