### ISSUE TITLE
inconsistent series color

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#456]
![image](https://user-images.githubusercontent.com/2334429/60525293-1b75cb00-9cbc-11e9-91e2-7ef2ca7a6249.png)

**Comment by NinaLoeterman** [comment]
Im an outreachy applicant may 2020 and I would be happy to work on this issue!

**Comment by kimberlythegeek** [comment]
Thanks @NinaLoeterman ! 🙂

**Comment by NinaLoeterman** [comment]
I cant seem to get yarn to download properly on my computer. I tried all the different ways of configuring it according to the docs but I get an error every time. Im not sure what to try next, would love some help. @kimberlythegeek @klahnakoski

**Comment by kimberlythegeek** [comment]
> I cant seem to get yarn to download properly on my computer. I tried all the different ways of configuring it according to the docs but I get an error every time. Im not sure what to try next, would love some help. @kimberlythegeek @klahnakoski

Can you tell me what approach/commands you're using to install yarn, and what kind of errors are you receiving?

**Comment by klahnakoski** [comment]
@NinaLoeterman   Are you able to talk on https://chat.mozilla.org/#/room/#perftest:mozilla.org  ?

**Comment by NinaLoeterman** [comment]
@klahnakoski sorry for the delay (its a holiday where I am.. )Im happy to talk now, are you still available?

**Comment by kimberlythegeek** [comment]
@NinaLoeterman if you join the above channel, there are people onling (including myself) who could be of assistance

**Comment by ArifaMujawar** [comment]
I am an outreachy applicant, I would like to contribute to this issue. @NinaLoeterman Could you please help me get started with it. I have the project running locally.
