### ISSUE TITLE
Increase duration before warning when no new data for battery charts

### ISSUE THREAD

**Issue by davehunt** [mozilla-frontend-infra/firefox-health-dashboard#470]
The idle battery tests are now run once/week so we should change the warning when no data is seen for 3 days to something like 10 days.

![Screenshot_2019-07-10 Firefox Health Dashboard](https://user-images.githubusercontent.com/122800/60962631-94050900-a306-11e9-814b-f27d939678de.png)

**Comment by arnold-iakab** [comment]
@davehunt Done.
