### ISSUE TITLE
Replace Wikia with Fandom tp6 (desktop)

### ISSUE THREAD

**Issue by davehunt** [mozilla-frontend-infra/firefox-health-dashboard#474]
Due to the change in branding for this site, we've renamed it from wikia to fandom. Let's replace the existing wikia graph with one using the new fandom data. Here's some data: https://treeherder.mozilla.org/perf.html#/graphs?series=mozilla-central,2091120,1,10&series=mozilla-central,2091117,1,10

**Comment by arnold-iakab** [comment]
@davehunt Done.
