### ISSUE TITLE
Give permission to assign issues to arnold-iakab

### ISSUE THREAD

**Issue by arnold-iakab** [mozilla-frontend-infra/firefox-health-dashboard#485]
@arnold-iakab 
Please grant me permission to assign issus.

**Comment by klahnakoski** [comment]
@armenzg   may you add this?

**Comment by armenzg** [comment]
@arnold-iakab I've upped you to "Triager". I believe that should do this.

@klahnakoski I've upped you to Admin so you can also handle this kind of requests.

**Comment by klahnakoski** [comment]
@armenzg   thank you!  that was fast!  back to the beach for me!
