### ISSUE TITLE
Add CNN to TP6m (Android)

### ISSUE THREAD

**Issue by davehunt** [mozilla-frontend-infra/firefox-health-dashboard#521]
We now have CNN (warm and cold) results. Let's add these to the Android dashboard. Example of data can be found here: https://treeherder.mozilla.org/perf.html#/graphs?series=mozilla-central,2095580,1,10&series=mozilla-central,2098268,1,10

**Comment by airimovici** [comment]
I'm working on this

**Comment by klahnakoski** [comment]
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/73178355dad24c861a3b1d792de85c60f0eede03/src/android/config.js#L35
