### ISSUE TITLE
Remove Google Restaurants from config file

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#523]
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/73178355dad24c861a3b1d792de85c60f0eede03/src/android/config.js#L33

**Comment by klahnakoski** [comment]
It has all nulls, and it is not run either

**Comment by davehunt** [comment]
This may be restored after a re-recording, so we should hold off on removing it.

**Comment by davehunt** [comment]
We have results for Google Restaurants for Fennec v64 and GeckoView: https://treeherder.mozilla.org/perf.html#/graphs?timerange=2592000&series=mozilla-central,2101724,1,10&series=mozilla-central,1988182,1,10

**Comment by klahnakoski** [comment]
@davehunt  I am lost on what to do.  I suggest we do nothing; keeping the Google Restaurants, and showing an empty chart for the platforms that do not run it.

**Comment by davehunt** [comment]
This test has been restored.
