### ISSUE TITLE
Remove references to Chrome from tp6

### ISSUE THREAD

**Issue by davehunt** [mozilla-frontend-infra/firefox-health-dashboard#527]
We've been reporting these as Chromium since April, and may start running geniune tests against Chrome this quarter. To avoid confusion, we should remove the existing references to tests that refer to Chrome.

I believe this mean removing the 'chrome' sources referred to in:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/9358645d3e8e30f5409c119308745ec57008ab65/src/quantum/config.js#L360-L387

Also:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/9358645d3e8e30f5409c119308745ec57008ab65/src/quantum/config.js#L560

And:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/7d7cbfaad997399626ff4bb5a5b1ff97cae3c694/src/quantum/Quantum.jsx#L134

**Comment by klahnakoski** [comment]
We can not remove these "chrome" references. The Perfherder backend uses "chrome" for old series: We need this to look back a year.

**Comment by davehunt** [comment]
I think we may need to do this, as we'll soon be running tests against Chrome release. Perhaps this has a dependency on renaming the tests in Perfherder to 'chromium' though?

**Comment by klahnakoski** [comment]
We will require an example run of real-chrome-test to see if the signature is the same as the old-chromium-run-as-chrome-test.

**Comment by gmierz** [comment]
@klahnakoski the real-chrome signatures will be the same as the old chromium-run-as-chrome tests. Here's an example test run: https://treeherder.mozilla.org/#/jobs?repo=try&revision=698429c9e3c9a8a616196ef0f8db4501d3f369bb&selectedJob=263548388

**Comment by klahnakoski** [comment]
@gmierz   Maybe we can simply include a time component in the signature filter so that we can distinguish between these two.

**Comment by gmierz** [comment]
@klahnakoski that would be ideal! :)
Anything using '-chrome' from now to the future would be real-chrome data.

**Comment by klahnakoski** [comment]
We have the code to deal with this, the old chromium-labeled-as-chrome is further filtered by date.  We only need to ensure the future chrome is also filtered by date

**Comment by klahnakoski** [comment]
@davehunt I need just one perfherder example link to add it.

**Comment by davehunt** [comment]
@gmierz can you provide @klahnakoski with a perfherder link once we have the tests runnng on Chrome?
