### ISSUE TITLE
Create media playback results page for Firefox Preview

### ISSUE THREAD

**Issue by davehunt** [mozilla-frontend-infra/firefox-health-dashboard#531]
We have started running the media playback tests on Firefox Preview. Let's add an option to select Firefox Preview from the media playback details page at https://health.graphics/playback

**Comment by davehunt** [comment]
@airimovici could you have a look at this?

**Comment by airimovici** [comment]
@davehunt Sure, there will be a PR for this issue and also https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/536
