### ISSUE TITLE
Object(...)(...) is undefined in Benchmarks section of Quantum landing page

### ISSUE THREAD

**Issue by davehunt** [mozilla-frontend-infra/firefox-health-dashboard#535]
The Benchmarks section of the [Quantum landing page](https://health.graphics/quantum/64) is showing two errors of "Object(...)(...) is undefined":

![Screenshot 2019-08-27 at 14 24 46](https://user-images.githubusercontent.com/122800/63775175-b82ca180-c8d6-11e9-8e96-f4be3fbb9aee.png)

**Comment by klahnakoski** [comment]
These are old D3 charts that referenced some perfherder signature.  I am guessing there was a name change.
