### ISSUE TITLE
Ensure back and forward do not reload data

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#538]
Back and forward to/from detail and summary pages should not be reloading

**Comment by klahnakoski** [comment]
Moving to hash browser may help.  Maybe [cache everything](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/578) is easier?

**Comment by vaideshshank** [comment]
Shall I take up this issue if available?

**Comment by klahnakoski** [comment]
@vaideshshank  yes, you may take this issue.  I suspect it involves moving from `BrowserRouter` to `HashRouter` (which demands the URL parameters be in the URL fragment (after the hash (`#`))

If you go with `HashRouter` solution, then this dashboard becomes truly static, enabling caching, and even faster loading.

**Comment by vaideshshank** [comment]
Sure I will implement this solution. Thanks.

**Comment by vaideshshank** [comment]
> @vaideshshank yes, you may take this issue. I suspect it involves moving from `BrowserRouter` to `HashRouter` (which demands the URL parameters be in the URL fragment (after the hash (`#`))
> 
> If you go with `HashRouter` solution, then this dashboard becomes truly static, enabling caching, and even faster loading.

@klahnakoski should all the react routes be shifted to HashRouter finally ?

**Comment by klahnakoski** [comment]
@vaideshshank yes, if you decide to move to HashRouter, it must be done everywhere.  I am not certain about how this effects the links.  At the very least, take this in small steps:  Replace the BrowserRouter with HashRouter, and then explore all the things the break. This will give you a better idea of the overall work that must be done.

Remember, there is the option of keeping `BrowserRouter`, and storing chart state between page loads (using local storage to do that, or adding a library to help you with that).  This is more sophisticated, but worth learning if you plan to become an expert in frontend development.

The choice is yours.   I am here to answer you questions and guide you through the process.

**Comment by vaideshshank** [comment]
Okay I'll try out both the options so as to have a better idea of implementation and choose the best fit then.
Thanks for suggesting.

**Comment by vaideshshank** [comment]
> Remember, there is the option of keeping `BrowserRouter`, and storing chart state between page loads (using local storage to do that, or adding a library to help you with that). This is more sophisticated, but worth learning if you plan to become an expert in frontend development.

Using this approach, should we associate some expiry time with the states so as to call the APIs again when the user switches back and forth between the pages beyond this time ?

**Comment by klahnakoski** [comment]
@vaideshshank  In the case of keeping `BrowserRouter`: When a user navigates backward/forward the charts will use local storage to display content immediately; at the same time the regular loading process will re-fetch data from the backend, replacing the chart content when new data is available.  If it has been a long time since a page has been loaded then the charts will show old data until the new data arrives; which is ok.  The majority of the work is caching the chart content for immediate display; ensuring the data is fresh is a minor adjustment atop the main feature.

**Comment by vaideshshank** [comment]
Sure. This would work fine.

**Comment by vaideshshank** [comment]
@klahnakoski while resolving this issue, whenever I try to pass previously fetched data from ```localStorage``` to the chart component from different graphs, I am getting the raw error message of 'This item has been missing the data for 3 days' as shown in this picture. 
![Capture](https://user-images.githubusercontent.com/42419232/72770426-d4cdcb00-3c23-11ea-8c79-1fcff129deae.PNG)

On digging into the state and props of chart component, I got to know that the property ```x``` within ```data``` array of property ```data.datasets``` under ```cjsOptions``` in the chart component was getting a value ```0``` when previously saved data was being passed from ```localStorage```. On the other hand during the normal http request of website after clearing the ```localStorage``` this property was being set perfectly with a date value. It can be seen through react devtools image I have attached below.

Note : I have performed this test for Bugzilla graph under Android. On left side, ```localStorage``` was cleared and on the right data was prefetched from ```localStorage```
![Capture](https://user-images.githubusercontent.com/42419232/72770923-583bec00-3c25-11ea-94a2-968466b68fd2.PNG)

Please suggest a solution to this issue if possible, to proceed further solving the main issue.

**Comment by klahnakoski** [comment]
@vaideshshank The best way to move forward is to make a PR with your changes so we can discuss the code. Prefix the PR with "WIP" for "Work in Progress".

The Bugzilla chart has a different datasource than the performance charts, so I would ignore it while trying to get things working.   

I have also recently pushed a number of PRs, I hope your local changes merge easily enough.

**Comment by JM-Mendez** [comment]
Hi @kimberlythegeek, I'm an Outreachy May 2020 applicant. I would like to a chance at this issue if you still have spots available.

**Comment by kimberlythegeek** [comment]
@vaideshshank Hi there--are you still working on this?
