### ISSUE TITLE
Add 'chrome' release tests to health dashboard

### ISSUE THREAD

**Issue by gmierz** [mozilla-frontend-infra/firefox-health-dashboard#542]
This bug is to add 'chrome' tests to the health dashboard and this depends on the changes in issue #527 (either removing the old data, or renaming it) since it has old data which uses the same signature. The test names will be similar to 'chromium' tests but with '-chromium' replaced with '-chrome'. Here is an example test set: https://treeherder.mozilla.org/#/jobs?repo=try&revision=698429c9e3c9a8a616196ef0f8db4501d3f369bb&selectedJob=263548388

**Comment by klahnakoski** [comment]
This example is showing Try branch, 

![image](https://user-images.githubusercontent.com/2334429/65383130-75e05f80-dcde-11e9-82ae-016343a63960.png)
