### ISSUE TITLE
Move framework/branch expressions from platform to suite

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#565]
There are many expressions in the config files that specifiy the framework and repo:

```
eq: {
    framework: 10,
    repo: 'mozilla-central',
}}
```

these really should be paired with the test suite filter, not the the platform filter, because suites belong to a framework.

**Comment by PaliwalArpit** [comment]
I would like to take this, as my first contribution to open source, can you please provide more details and what needed to be done in this?

**Comment by klahnakoski** [comment]
@PaliwalArpit 

Mozilla runs many performance tests. These tests are grouped into "suites", each suite is the same test with different parameters.  For example, there is a cold page load suite, which gets run on many different sites [example](https://health.graphics/quantum/tp6?test=warm-loadtime&platform=win64&past=month&ending=2019-10-27).  Each suite belongs to a "framework".  In the example, the framework is called "raptor", and is given the id of 10 (`framework==10`).  This dashboard is primarily about these raptor tests, but you can find others.

These tests, suites and frameworks are run on multiple platforms; windows, mac, linux, plus a few android variations, those platforms are further distinguished by how Firefox is complied, or what configuration was set.  These tests are also run on different versions of Firefox, called branches. 

Looking at [a config file](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/quantum/config.js)  you can see the platform filters, like:

```
    platformFilter: {and: [
        {or: [
          { eq: { platform: 'windows10-64', options: 'pgo' } },
          { eq: { platform: 'windows10-64-shippable', options: 'opt' } },
        ]},
        { eq: { framework: 10, repo: 'mozilla-central' } },
      ]},
```

This filter is locating the 64bit version of Firefox for windows; compiled with pgo (program guided optimization) or opt (optimized flag on). Also, it is limiting itself the tests run on mozilla central - the main branch of Firefox, and limiting itself to the Raptor tests (framework=10).

This is a bit messy: Framework is in this filter, but there is no mention of the suite, or tests. Suites and frameworks should be together because they both group tests; Technically, we can say "framework grouping is functionally dependent on suite grouping".  

The framework and suite *DO* come together, eventually.  The config file also [merges the various filters](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/770f8f9b20f5d6877834cb78cf04d5940abea974/src/quantum/config.js#L730) to provide all combination of suite/test and platforms of interest to the dashboard.  Only because this config file is only interested in one framework, Raptor, does this combining logic even work.

Your mission, is to remove all mention of framework (and repo) from the machine platforms, and add them to any filter that mentions suite.

**Notes**
 
I am here to guide you.  Feel free to open an incomplete PR (commit and push with `--no-verify`) so we can discuss code specifically. 

You can use the browsers debugger to follow the logic at the bottom of the file. Browser debuggers are a bit primitive: Only frame variables are accessible to the debugger.  Change a line like

```
const TP6_TESTS = selectFrom(TP6_SITES_DATA.data)
...
```

to
 
```
const temp = = selectFrom(TP6_SITES_DATA.data);
const TP6_TESTS = temp
...
```

Which creates a `temp` local variable, which you can inspect in the Watches section of the debugger:

```
temp.toArray()
```

which can show you the contents of `temp`

**Comment by HariShyamU** [comment]
Can I take this up if @PaliwalArpit is busy or unavailable?

**Comment by klahnakoski** [comment]
@HariShyamU  I believe @PaliwalArpit is working on this

**Comment by klahnakoski** [comment]
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/595

**Comment by PaliwalArpit** [comment]
@HariShyamU Please go ahead with this, my workload has significantly increased. Let me know if you won't take it still?

**Comment by Aniruddha-0812** [comment]
Is anyone working on this issue I am a complete newbie and wants to make my first contribution to the open source....I am having some doubts:
1] I cloned the desktop firefox at first and run the command ./mach build everything's done so for contributing to this issue i need to clone this project too or it's already available in the folders i cloned before ?
2] I am familiar with basics of node js is any other requirement for working on this issue ?

**Comment by klahnakoski** [comment]
@Aniruddha-0812  I have a number of PRs to review and merge, and I have time to work on them today.  Let me get back to you about the state of things.

**Comment by klahnakoski** [comment]
done
