### ISSUE TITLE
Add support to "Filter out noise" in PerfherderGraphContainer

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#57]
This is an old screenshot but it pictures the problem quite clearly.
We want to support this in PerfherderGraphContainer.

[1]
![image](https://user-images.githubusercontent.com/44410/36807491-25353c2c-1c91-11e8-828c-1f032a391ab1.png)

**Comment by armenzg** [comment]
I did [something similar](https://github.com/mozilla/firefox-health-dashboard/commit/643ff3bf1a710dbf1f9a07b9b76f5235bfc21561#diff-e382eb877fac5502593e9b6b96d9b488R73) to this when adding the subbenchmarks code.

I've marked this high cost since the code that needs touching is [the class PerfherderWidget](https://github.com/mozilla/firefox-health-dashboard/blob/master/src/quantum/perfherder.js) which digitard wrote and it is not a simple piece of code.

I think the changes should happen here:
https://github.com/mozilla/firefox-health-dashboard/blob/master/src/quantum/perfherder.js#L52-L133

The data that each of these graph fetches comes from [the backend](https://firefox-health-backend.herokuapp.com/api/perf/herder?framework=1&signatures=9525bb9b68bda10ed26b7c1999ba40830827c792&signatures=729285324ec4b164b8d3ecec42c2fdb344f7e581&signatures=1d2a194fc59a1e8a7635d05f9ecac80a73770bb5&signatures=a97a6a22157860fba4f5668be057d65b1aed6166).

**Comment by armenzg** [comment]
We should add support for this in PerfherderGraphContainer.

Let's first switch to PerfherderGraphContainer and see how things look with Chart.js

The devtools dashboard has something similar which they call "filter out noise".

**Comment by armenzg** [comment]
This is a feature that the DevTools also added to their dashboards.
Outliers show up as gray dots:
<img width="45" alt="image" src="https://user-images.githubusercontent.com/44410/49615249-f0700680-f97a-11e8-8890-0af7fac04013.png">

Alexander said it was a feature that was more important on the early days when the subtests were more noisy.

**Comment by klahnakoski** [comment]
see https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/304
