### ISSUE TITLE
Show correct links in graph tooltip for fenix

### ISSUE THREAD

**Issue by airimovici** [mozilla-frontend-infra/firefox-health-dashboard#570]
The tooltip links from PerfherderGraphContainer have `mozilla-central` as hardcoded repo. This does not work for fenix tests, which are on the `fenix` repo.

**Comment by divyanshu-rawat** [comment]
@airimovici is this issue open to work on ?

**Comment by airimovici** [comment]
@divyanshu-rawat it is available. If you want to work on it and have any questions I can help you with that.

**Comment by divyanshu-rawat** [comment]
cool, 🎉 Happy to give back something to the community @airimovici , let me know what it is all about?

**Comment by airimovici** [comment]
@divyanshu-rawat 
Basically, we have these graphs (PerfherderGraphContainer) in several pages and they show results from tests. When hovering on a point from one graph, there is a tooltip with info about that result that also contains some external links.

![graph-tooltip-rectangle](https://user-images.githubusercontent.com/51707553/71096422-f10ac200-21b6-11ea-9ac6-84ac8f221f74.png)

[Example of page with these type of graphs](https://health.graphics/playback/details?platform=win-aarch64&browser=firefox&encoding=VP9&past=week&ending=2019-12-18)

For a while we only had tests from a single repo: `mozilla-central`
The reason for the existence of this bug is that lately there are some tests that are from another repo (`fenix`), and the repo is hardcoded when creating the external links.

[Example of page where the external links in the tooltip are broken](https://health.graphics/playback/details?platform=p2-aarch64&browser=fenix&encoding=VP9&past=week&ending=2019-12-18)
