### ISSUE TITLE
Ensure ? opens new tab

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#577]
Upon clicking "?"  

![image](https://user-images.githubusercontent.com/2334429/66488423-deb82d80-ea7b-11e9-85e6-781a98793d71.png)

the page redirects to documentation.  It should open a new page instead.

**Comment by niklabh** [comment]
This is on which page

**Comment by niklabh** [comment]
Here is a pull request https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/580
