### ISSUE TITLE
Cache everything

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#578]
The signatures are stored for subsequent page visits because they do not change much.  If we can, somehow, signal there is more data for the charts, then we can also cache the data and use the signal when data-since-last-visit arrives. 

Can we key all charts on last_updated, so React knows when to update?

**Comment by klahnakoski** [comment]
This can allow live view, if we poll for more data periodically.

**Comment by kingsham** [comment]
I want to work on this but what file are you referring to?

**Comment by kimberlythegeek** [comment]
@kingsham what I believe he is saying is that, every time a chart is updated, to store this value somewhere, then subsequently add logic in React to decide when it should update again

I am new to this project and still learning the code base, but I will help as much as I am able!

**Comment by kingsham** [comment]
yea I get that but what file, in particular, is he talking about, there's a ton of files so which one in particular?

**Comment by klahnakoski** [comment]
@kingsham  this bug is particularly difficult.  You may try if you like.  

There is a variable that holds all the data coming from perfherder:

https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/99673b51474601320f791053fe024dfbac7e99f2/src/vendor/perfherder.js#L215

The first step is to replace that variable with local storage of some sort; hopefully when successful, you will be able to move from page to page without much network activity.  The rest of the problem is a bit harder.

Each series should be paired with a timestamp that you can use to track freshest data.  If the data is not fresh, then new promises are launched to get data from perfherder.  When the promises resolve, the local storage is updated with a new timestamp.  The react components that consume the local storage should have a timestamp parameter; used as a signal to re-render.
