### ISSUE TITLE
Busted link

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#582]
The "?" link on page https://health.graphics/android is wrong. it should include `.md` and read

https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/docs/about-pageload.md#about---site-load-times

Please fix the link, and ensure it opens a new page, rather than leaving the dashboard

**Comment by melvin2016** [comment]
I will work on this.

**Comment by melvin2016** [comment]
PR Done. @klahnakoski
