### ISSUE TITLE
Android page is causing a critical error

### ISSUE THREAD

**Issue by davehunt** [mozilla-frontend-infra/firefox-health-dashboard#590]
Trying to load https://health.graphics/android takes a long time to load, shows missing data, and then eventually displays the message:

> There has been a critical error. We have reported it. If the issue is not fixed within few hours please file an issue: https://github.com/mozilla/firefox-health-dashboard/issues/new

I did not wait a few hours, sorry. 😳

**Comment by klahnakoski** [comment]
looking now
