### ISSUE TITLE
Nimbledroid is no longer uploading Nightly builds

### ISSUE THREAD

**Issue by mcomella** [mozilla-frontend-infra/firefox-health-dashboard#591]
The https://health.graphics/android dashboard no longer has the latest Nightly Nimbledroid builds: it stops at Oct. 11. According to Colin, the Nightly app ID changed from `org.mozilla.fenix` to `org.mozilla.fenix.nightly`, which could have caused the problem. fwiw, the latest Nightly Nimbledroid runs are now [available here](https://nimbledroid.com/dashboard/Mozilla/nimbledroid-admin@mozilla.com/org.mozilla.fenix.nightly/6b5dbddf-86f2-42e8-bf2d-58044c796b5c...c32ae9eb-dae6-4e69-bd34-072561e3b5a2?os_version=android5).

We're tracking for our own purposes here: https://github.com/mozilla-mobile/perf-frontend-issues/issues/12

**Comment by mcomella** [comment]
This will be blocked on our final set-up for Nimbledroid uploads: https://github.com/mozilla-mobile/perf-frontend-issues/issues/20

**Comment by mcomella** [comment]
Our new nightly ND set-up is complete, unblocking this work: the dashboards are available here https://nimbledroid.com/dashboard/Mozilla/nimbledroid-admin@mozilla.com/org.mozilla.fenix.nightly/6b5dbddf-86f2-42e8-bf2d-58044c796b5c...c32ae9eb-dae6-4e69-bd34-072561e3b5a2?os_version=android5

@klahnakoski I've heard you are the one to ask about correcting the health.graphics dashboards: can you update the dashboard to pull from the our new Nimbledroid URL?

**Comment by klahnakoski** [comment]
@mcomella yes I am the one to fix this.

**Comment by klahnakoski** [comment]
@mcomella 

The nimbledroid data is pulled with another repo.  The code starts here:

https://github.com/mozilla/firefox-health-backend/blob/master/src/scripts/fetchNimbledroidData.js#L55

it's a bit of a maze, here is the config:

https://github.com/mozilla/firefox-health-backend/blob/master/src/configuration.js

I point you to this, in case it does not work

**Comment by klahnakoski** [comment]
@mcomella   I am going to need a new URI and maybe API key to get this product

please continue the discussion over at  https://github.com/mozilla/firefox-health-backend/issues/71

**Comment by armenzg** [comment]
@mcomella we've landed a backend change and I've fetched the data from the new user.
Only data for the nimbedroid-admin user is being used.
<img width="688" alt="image" src="https://user-images.githubusercontent.com/44410/69673191-c8842200-1067-11ea-9167-654fd58991f5.png">

**Comment by mcomella** [comment]
@armenzg Are you fetching the Firefox Preview nightly builds? I only see the Reference Browser builds on this dashboard.

The nightly builds should be available here: https://nimbledroid.com/my_apps/org.mozilla.fenix.nightly?a=359c5737-9cf5-4b01-82f9-6224c3c4e13d#summary

**Comment by armenzg** [comment]
I will let @klahnakoski to follow up.

I see that there's data in the backend:
https://firefox-health-backend.herokuapp.com/api/android/nimbledroid?product=org.mozilla.fenix.nightly&version=3

**Comment by klahnakoski** [comment]
This appears to be working
