### ISSUE TITLE
Geomean pageload not showing

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#593]
Due to the loss of a reference number, the geomean shows nothing

https://health.graphics/android

**Comment by davehunt** [comment]
Let's switch the reference number to fennec68. Here's some example data: https://treeherder.mozilla.org/perf.html#/graphs?highlightAlerts=1&series=mozilla-central,2129484,1,10&series=mozilla-central,2129480,1,10&series=mozilla-central,2129100,1,10&timerange=5184000
