### ISSUE TITLE
Lazy load material ui icons?

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#610]
Looking at https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/316 (which is old), it seems the icons make up a large part of the bundle size

    @material-ui\icons: 4.87 MB (44.2%)

Can the icons be separated into their own bundle?

**Comment by agrawal-d** [comment]
I am interested in taking this issue up. Could you please tell me a bit more about how I should go about it?

**Comment by klahnakoski** [comment]
@agrawal-d   yes please! take this.

**Comment by agrawal-d** [comment]
@klahnakoski it seems this issue is mostly related to Webpack, which I do not have experience with. I wasn't aware of it while taking the issue. I am unassiging myself. Thanks.

**Comment by Manish-Giri** [comment]
Hi, I'd like to give this a shot.

**Comment by klahnakoski** [comment]
@Manish-Giri   yes please, take this.  The code already splits some chart types into separate files, so I imagine the same can be done for the icons.

**Comment by vaideshshank** [comment]
@klahnakoski any progress in the issue so far? Can I work on resolving the issue?

**Comment by Manish-Giri** [comment]
Yes, I'm still working on it.

**Comment by vaideshshank** [comment]
Okay @Manish-Giri

**Comment by klahnakoski** [comment]
@Manish-Giri hows is this going?  

I was making a derivative of this project [count-bugs](https://github.com/klahnakoski/count-bugs); chopping out all things I do not need; leaving just one chart.  The complied size is still 670K, which is mostly these icons. You work here will be valued there too.

**Comment by Manish-Giri** [comment]
@klahnakoski I had worked quite a bit on this last month, but then I had to step away for a few weeks for interview prep. I'll get back on this right away. I had also listed out a few things(questions) I wanted to run by you.

Sorry for the delay.

**Comment by Romicodes** [comment]
@klahnakoski ,  any chance I could pick this up for Outreachy  May 2020?

**Comment by Romicodes** [comment]
@klahnakoski  any chance I could pick this up for Outreachy May 2020?

**Comment by klahnakoski** [comment]
@Romicodes - you have been assigned!  Please look how other modules are done now.

**Comment by kimberlythegeek** [comment]
Hello @Romicodes ! Thanks for your interest. I am the other mentor for this project, and can answer any questions you may have, as well as perform code reviews.

**Comment by Romicodes** [comment]
thank you @kimberlythegeek  I am in the process of looking at how other modules are lazy loaded and will be in touch shortly  with questions!

**Comment by Romicodes** [comment]
@kimberlythegeek , I was able to go over the project, start it at port 5000 and my suggestion to reduce  the size of the material UI icons is to use code splitting since we are using webpack. Manually split code using entry configuration. Please let me know your thoughts !

**Comment by kimberlythegeek** [comment]
@Romicodes hey there 👋🏻 Can you push your code changes so that I can see them? You can push to your own fork and send me the URL, or open a pull request tagged Work in Progress

How familiar are you with git?

**Comment by Romicodes** [comment]
@kimberlythegeek ,  yes am familiar with Git, but before that, I am unable to create a production build to record  build sizes of various modules! Inputs appreciated.

**Comment by Romicodes** [comment]
@klahnakoski , Is this still open for Outreachy?  I was able to achieve a reasonable measure of success with bug and would like to create a pull request and Project Request .

**Comment by Romicodes** [comment]
@klahnakoski @kimberlythegeek Is this still open for Outreachy? I was able to fix this bug and would like to create a pull request and Project Request .

**Comment by kimberlythegeek** [comment]
@Romicodes unfortunately I have had to make the difficult decision to withdraw my project from this round.
