### ISSUE TITLE
Add Chrome results for media playback tests

### ISSUE THREAD

**Issue by davehunt** [mozilla-frontend-infra/firefox-health-dashboard#616]
Now that https://bugzilla.mozilla.org/show_bug.cgi?id=1554967 is resolved we have Chrome results for media playback tests. @airimovici could you coordinate with @marianrai adding these to the summary page so we can visualise how we compare with Firefox desktop?

**Comment by airimovici** [comment]
Of course @davehunt 
I'll add a new section to the [video playback summary page](https://health.graphics/playback), just like the ones that already exist, like `Firefox (Desktop)` (see image below). I will make sure we see correct data on `Details page` also: https://health.graphics/playback/details

![playback-summary](https://user-images.githubusercontent.com/51707553/70513527-7bf61780-1b3a-11ea-807f-221a92ad915f.png)

**Comment by airimovici** [comment]
The Chrome tests were added and can be seen here: https://health.graphics/playback/
