### ISSUE TITLE
Switch between nightly and release

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#621]
We currently report numbers off of central.  It would be nice to report from the other branches too.

Do we do this by adding yet-another-dimension?

**Comment by annlinros** [comment]
Hi @klahnakoski  and  @kimberlythegeek ;
Could you please elaborate on the issue ?
I would like to contribute.

**Comment by kimberlythegeek** [comment]
Currently the results that are displayed are from mozilla-central only, which is the nightly branch of firefox. It is updated twice a day with new pushes, so it is less stable and changes frequently

we would also like to show test results for the release branch of firefox

This could be done in a variety of ways. displaying both at the same time could be noisy. Potentially have a toggle to switch between the two, or perhaps a filter have the option to see both at once. I'm not sure if that would be useful or a desired behavior (@klahnakoski?)

**Comment by kimberlythegeek** [comment]
I am fairly new to this project so I am still learning the code base myself, but I will do my best to help you navigate

**Comment by annlinros** [comment]
Thank you so much @kimberlythegeek.
I guess this feature is supposed to be implemented under windows/32 or windows/64 ?

**Comment by kimberlythegeek** [comment]
I believe the request should include Android as well, but I could be mistaken

**Comment by annlinros** [comment]
@kimberlythegeek ok. Could you guide me as to where to start first with this task ?
or is there any other good first issues?

**Comment by kimberlythegeek** [comment]
I believe this is a little more involved and may not be a good place to start. I will be filing more issues soon, but you can also contribute to [Perfherder](https://treeherder.mozilla.org/perf.html), another dashboard that is outside the scope of the internship, but has many open bugs to choose from: https://bugzilla.mozilla.org/buglist.cgi?product=Tree%20Management&component=Perfherder&resolution=---&list_id=15132483

**Comment by annlinros** [comment]
@kimberlythegeek  Sure! Thanks :)

**Comment by kimberlythegeek** [comment]
@annlinros when commenting on a bug in Bugzilla, could you also :needinfo me, by checking the box at the bottom of the Bug page that says "Request information from:" , and enter my email ksereduck@mozilla.com

I will be keeping an eye on the bug list, but this ensures I receive an email and can respond more quickly

**Comment by annlinros** [comment]
@kimberlythegeek thank you so much. I will have to first get familiarised with Bugzilla though.

**Comment by kimberlythegeek** [comment]
@annlinros yes, it is a bit confusing. I do not use it often so even I don't know everything about it. Please reach out if you have questions, you can also email me or send private messages in Riot, my username there is also kimberlythegeek:

https://riot.im/app/#/room/#treeherder.org
https://wiki.mozilla.org/Matrix

**Comment by kimberlythegeek** [comment]
This may help: https://bugzilla.readthedocs.io/en/latest/using/index.html

**Comment by klahnakoski** [comment]
@annlinros @kimberlythegeek   This issue has two main parts.  The most difficult is deciding HOW to visualize the two different modes (nightly or central), the second is to implement it in the backend.  The second part should not be hard:  Almost all charts run off of Perfherder, and the only different between the two modes is the choice of `repo` (`mozilla-central` or `mozilla-beta`).  This is the same for Android, Windows, Linux and Mac.

The first step is to make a React widget, or something, that we can review to see how you propose we switch bewteen these two modes.

**Comment by annlinros** [comment]
Thanks @klahnakoski  and  @kimberlythegeek 
I will look into it.

**Comment by yaeluria** [comment]
Hi @klahnakoski and @kimberlythegeek. I'm an Outreachy 2020 applicant and would like to work on this issue if @annlinros is not already working on it.

**Comment by annlinros** [comment]
@yaeluria  you could start with it. I’m bit busy with other time commitments..

**Comment by yaeluria** [comment]
Okay. Thanks @annlinros.
