### ISSUE TITLE
Remove Telemetry section

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#623]
We will not need the telemetry section until the next release is reporting the numbers.

**Comment by armenzg** [comment]
Will we need the Telemetry section again?
I was asked about the two Redash queries that are costing some money and I stopped the refreshing of them.

**Comment by armenzg** [comment]
Notes from @wlach  in case we were to re-enable the use of those queries:
> They aren't frequently scheduled but it looks like they scan quite a bit of data when they are (BigQuery is ~5$/TB scanned). It also appears that they're not being frequently looked at.
> If I were going to optimize these queries, I'd probably look into sampling and/or looking at a smaller date range:
> https://docs.telemetry.mozilla.org/cookbooks/bigquery/optimization.html#how-to-improve-both-query-speed-and-cost

**Comment by klahnakoski** [comment]
@armenzg  It is good you have stopped the queries.  We will wait for someone to complain.
