### ISSUE TITLE
Media Playback - Criterion change

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#626]
The media plackback should color according to 

* greater than 1 dropped frame for 1080p 30fps (or smaller, or slower) - RED 
* greater than 1 dropped from on all others - YELLOW

**Comment by airimovici** [comment]
@klahnakoski I'm not sure if I understand this issue correctly and I have some questions:
1. By slower, do you mean speeds below 1x playback speed?
2. I'm not sure sure what are the differences between the current criterion and the one we should change to. I will write what I understand it changes, please point out if I am missing an edge case.
From my understanding, the differences are:
	- 1080p 60fps, 1440p and 2160p can be at maximum yellow (now it can also be red)
	- for the example in the attached image, it should be red according to the new criteria.
![test-example](https://user-images.githubusercontent.com/51707553/71913843-01dca100-3181-11ea-9345-008d9b34121e.png)

**Comment by klahnakoski** [comment]
@airimovici  The old criterion only cared about 1x playback speed.  The new criterion will go red on slower playback too.  The resolution is now in the criterion too: before high res failure was marked red, now it can only be marked yellow.  Here is the old logic.   

          lookupType[
            selectFrom(speeds)
              .map(({ speed, loss }) => {
                if (speed === 1) {
                  if (missing(loss)) return 3;
                  if (loss > 1) return 2;

                  return 0;
                }

                if (missing(loss) || loss <= 1) return 0;

                return 1;
              })
              .max()
          ],
