### ISSUE TITLE
Add descriptive page titles

### ISSUE THREAD

**Issue by davehunt** [mozilla-frontend-infra/firefox-health-dashboard#628]
When attempting to navigate back without cycling through all pages (which is very slow) I'd like to be able to jump back to a previously visited page. The problem is, all pages have the same title, which makes this very difficult.

![Screenshot 2019-12-12 at 22 06 04](https://user-images.githubusercontent.com/122800/70753057-ce4a5a80-1d2b-11ea-93bb-a83c86a7bab5.png)

**Comment by Fcmam5** [comment]
Can I work on this?

**Comment by klahnakoski** [comment]
@Fcmam5 yes please!
