### ISSUE TITLE
Change "fennec68" to "ESR"

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#633]
We will change naming convention from "fennec68" to "ESR"

**Comment by airimovici** [comment]
According to a comment from Dave in this PR: https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/615. I renamed `fennec68` to `Firefox ESR`.  This change should already be merged and can be checked on [health.graphics](http://health.graphics).

Should I change the browser display name from "Firefox ESR" to "ESR" as this Issue suggests or should I let it "Firefox ESR", like it is right now? 


This is the comment I referred to above:
> As discussed, we're going to adjust this to have a section for each test (idle, idle-background, speedometer). Within each section we'll have a graph for each device (Moto G5, Pixel 2). These graphs will show results for all targets (GeckoView Example, Firefox ESR, Firefox Preview). This will allow for easy comparison between our applications on each device.

**Comment by klahnakoski** [comment]
Use the shorter "ESR" name only if "Firefox ESR" is too long for the charts, or if there are too many "Firefox" words on a chart.  I

If it look good, do not change it
