### ISSUE TITLE
Remove Pixel 2 (arm7) from graphs

### ISSUE THREAD

**Issue by davehunt** [mozilla-frontend-infra/firefox-health-dashboard#638]
We've stopped running perf tests against 32bit builds on Pixel 2 via [bug 1604547](https://bugzilla.mozilla.org/show_bug.cgi?id=1604547). Let's remove the associated data from our visualisations to reduce the distractions this may cause.

**Comment by airimovici** [comment]
This issue was addressed in PR https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/615
