### ISSUE TITLE
Performance issue on media playback summary page

### ISSUE THREAD

**Issue by airimovici** [mozilla-frontend-infra/firefox-health-dashboard#639]
This slowdown issue was raised here: https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/632#pullrequestreview-334073165

**Comment by klahnakoski** [comment]
@airimovici Are you working on this?

**Comment by airimovici** [comment]
@klahnakoski I did some tests on it and managed to drop it down from 1:30-1:50 min to 30-35 sec with limiting the scanning of signatures.

**Comment by airimovici** [comment]
What I did was only scanning on the video playback signatures instead of all of them from perfherder. This reduced the signatures to scan on from ~60k to ~8k.

**Comment by klahnakoski** [comment]
@airimovici is there a PR for this?

**Comment by airimovici** [comment]
I created this PR: https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/658
