### ISSUE TITLE
Show browsers on single chart - Android page

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#652]
All charts should be comparing browsers, not platforms

![image](https://user-images.githubusercontent.com/2334429/73087650-d7892400-3ea0-11ea-812e-327e9d46a201.png)

**Comment by ajinkabeer** [comment]
Hello @klahnakoski, I am outreachy applicant. I would like to work on this. Can I get some more information about this issue?

**Comment by klahnakoski** [comment]
@ajinkabeer if you look at https://health.graphics/android you will see the above charts.  You will also see "Speedometer CPU power usage" which is done correctly.

Find the code responsible for showing the 'Speedometer" chart. Notice the code declares the rules for what to show in each series. It must change from showing one browser on many(2)  platforms, to showing one platform, on many browsers.  There is a question about what browsers to show:  Look at the power usage chart for hints.

During your exploration, be sure to click on the "show perfherder" button:  It will show the same data in a different frontend, called Perfherder.  Perfherder can be used to discover which browsers the Speedometer test is run on.

Make a Pull Request (use `--no-verify` to avoid the commit/push checks) on any change (even broken changes).  We can continue discussion about details there.

**Comment by ajinkabeer** [comment]
Thanks for the detailed explanation @klahnakoski. I am in the process of familiarizing myself with the codebase by reading through it. I would definitely make a PR once I make any meaningful change. :)

**Comment by kimberlythegeek** [comment]
Hi, @ajinkabeer ! I am the other mentor for the Outreachy project. Feel free to ping me with any questions you may have, as well as request code reviews from me

**Comment by ajinkabeer** [comment]
Hello @kimberlythegeek, thanks for the opportunity. I will keep in touch with you.
