### ISSUE TITLE
Show "Windows 64" in title 

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#653]
https://health.graphics/windows/64  looks like 

![image](https://user-images.githubusercontent.com/2334429/73087844-22a33700-3ea1-11ea-9fec-908582f34dbd.png)

have it say "Windows 64".  Do the same for the 32 bit version

**Comment by the-pro** [comment]
hello sir, i want to take this issue if it is still available.

**Comment by klahnakoski** [comment]
@the-pro  yes please.  it's yours now.

**Comment by the-pro** [comment]
So i tried to make the change. Tell me if this was what you needed:
![windows](https://user-images.githubusercontent.com/42973786/73136168-b5de9700-4070-11ea-9077-d1b7a772e2a1.png)

**Comment by klahnakoski** [comment]
@the-pro  Yes, that's what i am looking for.  Please make a PR

**Comment by the-pro** [comment]
Done.

**Comment by rimshach** [comment]
Hey , I read the comments and it seems like issue has been resolved however if it is still open I want to take this issue

**Comment by klahnakoski** [comment]
@rimshach yes. this is resolved
