### ISSUE TITLE
Show error panel if PerfherderGraphContainer has missing data for several days

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#66]
Sometimes, Perfherder will stop having recent data, however, the graphs do not make it easy to notice.

We need to add some code that would look for the most recent data point, determine if it's been longer than 3 days and show an error panel underneath it saying so.

See issue #68 for when it happened in the past.

Use the `ErrorPanel` component:
https://mozilla-frontend-infra.github.io/components/#errorpanel

**Comment by armenzg** [comment]
See #68

**Comment by aimenbatool** [comment]
@armenzg 
In my understanding, we have to check data and look for the recent date. If it is more than 3 days we have to show an error panel [here](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/containers/PerfherderGraphContainer/index.jsx#L51). 
Please correct me if I am wrong!

**Comment by armenzg** [comment]
You got it!
