### ISSUE TITLE
Change from coveralls to codecov.io

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#665]
Coveralls seems broken, and no longer can be used to sort  https://github.com/lemurheavy/coveralls-public/issues/1365

Change the `.travis.yml` file to use codecov.io instead

**Comment by js636f** [comment]
@klahnakoski may I work on this issue?

**Comment by kimberlythegeek** [comment]
Yes, thanks @js636f ! I am the other mentor on this project, feel free to ask me questions as well

**Comment by silvererudite** [comment]
hi @kimberlythegeek can you pls recommend me a good first bug as I dont see any unassigned ones now? I'm an outeachy applicant,also interested to contribute to the project

**Comment by js636f** [comment]
Thank you, @kimberlythegeek !

**Comment by kimberlythegeek** [comment]
Hi @silvererudite ! Yes, I apologize, I realize there are not many to choose from right now. Kyle and I are going to begin filing more bugs today. You can also look at Perfherder-related bugs. Perfherder is another react dashboard that is outside the scope of the internship, but there are many more issues to choose from!

Perfherder is part of Treeherder: https://treeherder.mozilla.org/perf.html

[Perfherder bugs](https://bugzilla.mozilla.org/buglist.cgi?product=Tree%20Management&component=Perfherder&resolution=---&list_id=15132483)

**Comment by kimberlythegeek** [comment]
@js636f You are quite welcome 🙂

**Comment by kingsham** [comment]
> Yes, thanks @js636f ! I am the other mentor on this project, feel free to ask me questions as well

I need help contributing to a project

**Comment by kimberlythegeek** [comment]
> I need help contributing to a project
Hi there--the best way to contribute is to look for unassigned bugs or issue's on a project's contribution page. We don't have many open issues for health.graphics (this project), but you can also contribute to [Perfherder](https://treeherder.mozilla.org/perf.html), another react dashboard. There are a lot more bugs to choose from. Simply comment and ask to be assigned. 

If you find a bug on bugzilla, please :needinfo me by check the box at the bottom of the page that says "Request information from" and enter my email: ksereduck@mozilla.com. I will receive an email notification and be able to respond faster

[unassigned Perfherder bugs](https://bugzilla.mozilla.org/buglist.cgi?cmdtype=runnamed&namedcmd=Perfherder%20Unassigned&list_id=15140577)

**Comment by klahnakoski** [comment]
I think this is done
