### ISSUE TITLE
Using new coverage bade on README.md

### ISSUE THREAD

**Issue by js636f** [mozilla-frontend-infra/firefox-health-dashboard#670]
@klahnakoski Now, when we use codecov, I think we need to update a coverage badge in README.md and use this:

`[![Coverage Status](https://codecov.io/gh/mozilla-frontend-infra/firefox-health-dashboard/branch/master/graphs/badge.svg)](https://codecov.io/gh/mozilla-frontend-infra/firefox-health-dashboard?branch=master)`

Instead of this:

`[![Coverage Status](https://coveralls.io/repos/github/mozilla-frontend-infra/firefox-health-dashboard/badge.svg?branch=master)](https://coveralls.io/github/mozilla-frontend-infra/firefox-health-dashboard?branch=master)`

If I'm right - I think this can be a good first issue for someone.

**Comment by katherine95** [comment]
I would like to work on this @js636f @klahnakoski @kimberlythegeek Kindly assign it to me.

**Comment by km-js** [comment]
I would like to work on this.
