### ISSUE TITLE
Removed Nimbledroid from backend

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#692]
I messed up and I removed the Heroku Redis add-on on the backend which contained Nimbledroid's historic data.

I can follow up with Heroku but I doubt we can recover it.

My apologies. A very dumb mistake.

**Comment by armenzg** [comment]
I assume at this point should I remove the Nimbledroid UI code?

**Comment by armenzg** [comment]
@airimovici @davehunt Heroku restored the Redis add-on with backed up data and the UI is working again.

Should we remove Nimbledroid from the UI? (You can use #693 to do so)

**Comment by davehunt** [comment]
@ecsmyth @mcomella do you have any objections to us removing Nimbledroid results from health.graphics?

**Comment by ecsmyth** [comment]
No objections

**Comment by armenzg** [comment]
Hi Dave, please merge the PR if satisfied and I will remove the Heroku Redis add-on with the Nimbledroid historic data.
