### ISSUE TITLE
Private domain & cloudflare

### ISSUE THREAD

**Issue by digitarald** [mozilla-frontend-infra/firefox-health-dashboard#721]
As I kickstarted the project, the health.graphics domain runs on my name and my free cloudflare acccount. Since August I am no longer with Mozilla.

Options:

1) Transfer the domain/account. It would be nice to cover my expenses for the domain so far.

2) Transfer the project to another domain (like Mozilla's allizom preview server)

Happy to hear other ideas and make any needed changes in cloudflare.

**Comment by davehunt** [comment]
Thanks for opening this issue @digitarald, I hadn't realised that you kickstarted health.graphics. I'll file a bug for ops to look into this and will provide a link here.

**Comment by davehunt** [comment]
I've opened https://bugzilla.mozilla.org/show_bug.cgi?id=1665896. I'm also going to follow up on your point on expenses.

**Comment by davehunt** [comment]
We have merged a patch with a banner announcing the potential retirement of health.graphics. This has been deployed to Netlify and can be seen at https://firefox-health-dashboard.netlify.app/ but it would appear that the health.graphics domain is not pointing to Netlify. @digitarald could you clarify the current domain configuration?

**Comment by digitarald** [comment]
@davehunt config is updated:

![image](https://user-images.githubusercontent.com/8599/99109678-07bfc180-259e-11eb-8683-cb6a92bf80cf.png)
