### ISSUE TITLE
Remove all remaining custom linting rules

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#75]
When I split the frontend and backend code I decided to leave a bunch of custom linting rules.
If we remove them all we will likely catch some bugs we could otherwise be introducing.

Removing the custom rules will require refactoring the code to meet the airbnb style guide.

This is also useful since IDE editors that including linting do not know how to handle linting rules within .neutrinorc.js

**Comment by klahnakoski** [comment]
is this related to https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/233#discussion_r242150317  ?

**Comment by armenzg** [comment]
We can either just remove the linting issues with the current rules OR also switch to react-lint.

**Comment by aimenbatool** [comment]
@sarah-clements  can you please explain this? 
In my understanding we need to follow what Hassan has mentioned in [this comment](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/233#discussion_r242150317).
Removing line 7-73 and then adding react-lint. 

Correct me if I'm wrong.

**Comment by sarah-clements** [comment]
> @sarah-clements can you please explain this?
> In my understanding we need to follow what Hassan has mentioned in [this comment](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/233#discussion_r242150317).
> Removing line 7-73 and then adding react-lint.
> 
> Correct me if I'm wrong.

yes, I'd do what Hassan is suggesting in that comment. When you change linting rules you will often see many lint errors in the terminal. You might be able to fix some with `yarn lint --fix` but others you'll need to fix before those changes get merged.

**Comment by aimenbatool** [comment]
Fixed in https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/281
