### ISSUE TITLE
Specific graphs to use metric-graphics baseline prop

### ISSUE THREAD

**Issue by sarah-clements** [mozilla-frontend-infra/firefox-health-dashboard#82]
In Quantum pages, replace the AWFY components (ONLY for 'Current Nightly vs Canary Dec. 2017' graphs) target line with a baseline (baseValue * targetRatio), using the metric-graphics 'baselines' prop. This might need to tie into issue #72 as removing the target line/data for this graph in the API results in a UI side effect of a persistent label appearing on the graph (normally only appearing on hover) even on mouse-out.

**Comment by armenzg** [comment]
These graphs were dropped after we decomissioned the AWFY service.
