### ISSUE TITLE
Update whiteboard tag for Quantum flow component with V61 release

### ISSUE THREAD

**Issue by sarah-clements** [mozilla-frontend-infra/firefox-health-dashboard#91]
The [qf:f61] tag should be replaced with [qf:f64] [here](https://github.com/mozilla/firefox-health-dashboard/blob/master/src/quantum/constants.js#L37) when 61 is released, as mentioned in [this](https://github.com/mozilla/firefox-health-dashboard/issues/22) issue.

**Comment by armenzg** [comment]
Firefox 61 is releasing on 2018-06-26

**Comment by armenzg** [comment]
It seems we missed this.

There will be a meeting this week to determine what the Quantum pages should show.
I will file a new issue if this comes up.
