### ISSUE TITLE
Photon perf graphs use data from all operating systems instead of Windows

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#95]
The photon performance graphs use data from *any* OS rather than windows 32-bit or windows 64-bit.

This:
https://telemetry.mozilla.org/new-pipeline/evo.html#!aggregates=median&arch=x86-64&cumulative=0&end_date=null&keys=&max_channel_version=nightly%252F61&measure=FX_NEW_WINDOW_MS&min_channel_version=nightly%252F58&processType=*&product=Firefox&sanitize=0&sort_keys=submissions&start_date=null&trim=0&use_submission_date=0
instead of:
https://telemetry.mozilla.org/new-pipeline/evo.html#!aggregates=median&arch=x86&cumulative=0&end_date=null&keys=&max_channel_version=nightly%252F61&measure=FX_NEW_WINDOW_MS&min_channel_version=nightly%252F58&os=Windows_NT&processType=*&product=Firefox&sanitize=0&sort_keys=submissions&start_date=null&trim=0&use_submission_date=0
OR:
https://telemetry.mozilla.org/new-pipeline/evo.html#!aggregates=median&arch=x86-64&cumulative=0&end_date=null&keys=&max_channel_version=nightly%252F61&measure=FX_NEW_WINDOW_MS&min_channel_version=nightly%252F58&os=Windows_NT&processType=*&product=Firefox&sanitize=0&sort_keys=submissions&start_date=null&trim=0&use_submission_date=0

**Comment by klahnakoski** [comment]
this is enabled now.  we will wait for specific views to request this feature.
